# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Interoperability helpers for correction measurement bundles.

REW and similar tools are happiest with boring files: delimited
frequency-response text and mono WAV impulse responses. Keep those
formats here so web handlers, CLIs, and future agent tools do not grow
their own subtly-different exporters.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

import numpy as np

from . import deconv, sweep


class InteropError(ValueError):
    """Export input is missing or malformed."""


def _curve_arrays(curve: dict[str, Any]) -> tuple[np.ndarray, np.ndarray]:
    try:
        freqs = np.asarray(curve["freqs_hz"], dtype=float)
        magnitude = np.asarray(curve["magnitude_db"], dtype=float)
    except (KeyError, TypeError, ValueError) as e:
        raise InteropError("curve must contain freqs_hz and magnitude_db") from e
    if freqs.ndim != 1 or magnitude.ndim != 1 or freqs.shape != magnitude.shape:
        raise InteropError("curve frequency and magnitude arrays must be 1-D matches")
    if freqs.size == 0:
        raise InteropError("curve is empty")
    if not np.all(np.isfinite(freqs)) or not np.all(np.isfinite(magnitude)):
        raise InteropError("curve contains non-finite values")
    if np.any(freqs <= 0):
        raise InteropError("curve frequencies must be positive")
    order = np.argsort(freqs)
    freqs = freqs[order]
    magnitude = magnitude[order]
    if np.any(np.diff(freqs) <= 0):
        raise InteropError("curve frequencies must be unique")
    return freqs, magnitude


def format_frequency_response_text(
    curve: dict[str, Any],
    *,
    title: str,
    source: str,
    include_phase: bool = True,
) -> str:
    """Render a generic REW-importable frequency-response text file.

    JTS currently stores smoothed magnitude curves in bundles, not
    acoustic phase. When `include_phase` is true we write a third
    phase column with 0 degrees and say so in the header. This keeps
    `.frd` consumers happy without pretending we have phase evidence.
    """
    freqs, magnitude = _curve_arrays(curve)
    lines = [
        f"# {title}",
        "# Generated by JTS correction bundle export",
        f"# Source: {source}",
        "# Columns: frequency_hz magnitude_db"
        + (" phase_deg" if include_phase else ""),
    ]
    if include_phase:
        lines.append(
            "# Phase is 0.0 because this bundle stores magnitude-only curves; "
            "export impulse-response WAVs when phase is needed."
        )
    for freq, mag in zip(freqs, magnitude, strict=True):
        if include_phase:
            lines.append(f"{freq:.6f}\t{mag:.6f}\t0.000000")
        else:
            lines.append(f"{freq:.6f}\t{mag:.6f}")
    lines.append("")
    return "\n".join(lines)


def write_frequency_response_text(
    path: Path,
    curve: dict[str, Any],
    *,
    title: str,
    source: str,
    include_phase: bool = True,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        format_frequency_response_text(
            curve,
            title=title,
            source=source,
            include_phase=include_phase,
        ),
    )


def sweep_from_meta(meta: dict[str, Any]) -> tuple[np.ndarray, sweep.SweepMeta]:
    """Regenerate the exact deterministic sweep described by a bundle."""
    try:
        f1 = float(meta["f1"])
        f2 = float(meta["f2"])
        duration_s = float(meta["duration_s"])
        sample_rate = int(meta["sample_rate"])
        amplitude_dbfs = float(meta["amplitude_dbfs"])
    except (KeyError, TypeError, ValueError) as e:
        raise InteropError("bundle sweep_meta is incomplete") from e
    return sweep.synchronized_swept_sine(
        f1=f1,
        f2=f2,
        duration_approx_s=duration_s,
        sample_rate=sample_rate,
        amplitude_dbfs=amplitude_dbfs,
    )


def impulse_response_from_capture(
    capture_path: Path,
    *,
    sweep_meta: dict[str, Any],
) -> tuple[np.ndarray, int]:
    """Recompute an impulse response from a raw bundle capture."""
    sweep_signal, meta = sweep_from_meta(sweep_meta)
    captured, sample_rate = sweep.read_wav_mono(capture_path)
    if sample_rate != meta.sample_rate:
        raise InteropError(
            f"{capture_path.name} sample rate {sample_rate} Hz does not "
            f"match sweep {meta.sample_rate} Hz"
        )
    ir = deconv.deconvolve(
        captured.astype(np.float64),
        sweep_signal.astype(np.float64),
        sample_rate=meta.sample_rate,
    )
    return ir.astype(np.float32), meta.sample_rate


def write_impulse_response_wav(
    path: Path,
    ir: np.ndarray,
    *,
    sample_rate: int,
    normalize: bool = False,
) -> None:
    """Write a mono float32 impulse response WAV.

    Float WAV keeps the deconvolved amplitude intact. Optional
    normalization is useful for tools that expect a visible peak, but
    the default preserves replay evidence.
    """
    from scipy.io import wavfile

    data = np.asarray(ir, dtype=np.float32)
    if data.ndim != 1:
        raise InteropError(f"impulse response must be 1-D, got {data.shape}")
    if normalize and data.size:
        peak = float(np.max(np.abs(data)))
        if peak > 0:
            data = (data / peak).astype(np.float32)
    path.parent.mkdir(parents=True, exist_ok=True)
    wavfile.write(str(path), int(sample_rate), data)
