# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""The bass candidate field: what a family must be, and what protects it.

The family here is the REAL one — generated by the sealed adapter from a
plant, then round-tripped through JSON — so the transform each rung claims is
the transform the alignment module composes, not a hand-copied number.
"""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import Any

import pytest

from jasper.bass_extension.adapters.sealed import SEALED_ADAPTER, SealedPlantFit
from jasper.bass_extension.candidate_field import (
    BassCandidateFieldError,
    bass_extension_summary,
    validate_bass_extension_field,
)
from jasper.bass_extension.refusals import BassExtensionRefusal
from jasper.bass_extension.targets import MARGINS

PLANT = SealedPlantFit(f0_hz=45.0, q0=0.707, fit_rms_db=0.3)
MARGIN = MARGINS["conservative"]
SHA = "a" * 64
OTHER_SHA = "b" * 64

#: A mutation that DELETES the key instead of replacing its value.
_DROP = object()


def bass_family() -> list[dict[str, Any]]:
    """The sealed adapter's own family, as JSON: deepest first, natural last."""
    return json.loads(
        json.dumps([
            asdict(target)
            for target in SEALED_ADAPTER.generate_family(PLANT, margin=MARGIN)
        ])
    )


def ladder_evidence(max_level_db: float, *, verdict: str = "pass") -> dict[str, Any]:
    """Row 3.4's artifact, reduced to the three fields admission turns on."""
    return {"sha256": OTHER_SHA, "verdict": verdict, "max_level_db": max_level_db}


def limiter_evidence() -> dict[str, Any]:
    return {"sha256": SHA, "verdict": "pass"}


def bass_extension_field(
    *, boosted: bool = False, **overrides: Any
) -> dict[str, Any]:
    """A valid field: the natural target alone, or the deepest rung with it.

    ``boosted`` attaches both protection evidences to the deepest rung, which
    is the only way a boosted member is carried at all.
    """
    family = bass_family()
    rungs = [{
        "target": family[-1],
        "max_level_db": 0.0,
        "lt_boost_db": 0.0,
        "protection": {"ladder": None, "limiter": None},
    }]
    if boosted:
        rungs.insert(0, {
            "target": family[0],
            "max_level_db": -6.0,
            "lt_boost_db": 6.0,
            "protection": {
                "ladder": ladder_evidence(-6.0),
                "limiter": limiter_evidence(),
            },
        })
    field = {
        "owner": {"role": "woofer", "channels": [0, 1]},
        "adapter_id": "sealed_v1",
        "margin_policy_name": MARGIN.name,
        "effective_plant": {
            "f0_hz": PLANT.f0_hz, "q0": PLANT.q0, "source": "seat_median_fit",
        },
        "rungs": rungs,
        "basis": {"round_id": "round-3", "bass_fit_sha256": SHA},
    }
    field.update(overrides)
    return field


def _mutate(field: dict[str, Any], path: tuple[Any, ...], value: Any) -> dict[str, Any]:
    """One minimal mutation, deep-copied so the fixture stays reusable."""
    mutated = json.loads(json.dumps(field))
    cursor: Any = mutated
    for key in path[:-1]:
        cursor = cursor[key]
    if value is _DROP:
        del cursor[path[-1]]
    else:
        cursor[path[-1]] = value
    return mutated


def test_a_natural_only_family_validates_and_costs_no_level():
    field = validate_bass_extension_field(bass_extension_field())

    assert [rung["target"]["target_id"] for rung in field["rungs"]] == ["natural"]
    assert field["rungs"][-1]["max_level_db"] == 0.0


@pytest.mark.parametrize("path, value", [
    # Understated headroom: every downstream bound — the graph proof's cap, the
    # seat-SPL stop, the excitation-cap comparison — is stated in this number.
    (("rungs", 0, "target", "boost_headroom_db"), 1.0),
    (("rungs", 0, "target", "boost_headroom_db"), 5.8),
    # A cost that is not this transform's.
    (("rungs", 0, "lt_boost_db"), 5.0),
    (("rungs", 0, "lt_boost_db"), 0.0),
])
def test_a_rung_may_not_understate_what_its_own_transform_spends(path, value):
    with pytest.raises(BassCandidateFieldError) as exc:
        validate_bass_extension_field(
            _mutate(bass_extension_field(boosted=True), path, value)
        )

    assert exc.value.reason is BassExtensionRefusal.TARGET_INVALID


def test_the_adapters_own_family_states_both_costs_the_reader_recomputes():
    """The generator and this reader land on one number, not two near it."""
    field = validate_bass_extension_field(bass_extension_field(boosted=True))

    assert field["rungs"][0]["target"]["boost_headroom_db"] > 0.0
    assert field["rungs"][0]["lt_boost_db"] > 0.0


def test_a_boosted_family_carries_the_level_its_ladder_measured():
    field = validate_bass_extension_field(bass_extension_field(boosted=True))

    assert field["rungs"][0]["max_level_db"] == -6.0
    assert field["rungs"][0]["protection"]["limiter"] is not None


@pytest.mark.parametrize("boosted,path,value,reason", (
    (False, ("adapter_id",), _DROP, BassExtensionRefusal.FIELD_MALFORMED),
    (False, ("adapter_id",), "ported_v9", BassExtensionRefusal.ADAPTER_UNKNOWN),
    (False, ("margin_policy_name",), "generous",
     BassExtensionRefusal.FIELD_MALFORMED),
    (False, ("owner", "channels"), [], BassExtensionRefusal.OWNER_INVALID),
    (False, ("owner", "channels"), [1, 1], BassExtensionRefusal.OWNER_INVALID),
    (False, ("owner", "role"), "", BassExtensionRefusal.OWNER_INVALID),
    (False, ("effective_plant", "f0_hz"), 400.0,
     BassExtensionRefusal.PLANT_INVALID),
    (False, ("effective_plant", "q0"), None, BassExtensionRefusal.PLANT_INVALID),
    (False, ("effective_plant", "source"), 3, BassExtensionRefusal.PLANT_INVALID),
    (False, ("rungs",), [], BassExtensionRefusal.TARGET_INVALID),
    (False, ("rungs", 0, "target", "fp_hz"), -1.0,
     BassExtensionRefusal.TARGET_INVALID),
    (False, ("rungs", 0, "target", "target_id"), "t9",
     BassExtensionRefusal.TARGETS_UNORDERED),
    (False, ("rungs", 0, "target", "boost_headroom_db"), 3.0,
     BassExtensionRefusal.PROTECTION_INVALID),
    (False, ("rungs", 0, "max_level_db"), -3.0,
     BassExtensionRefusal.TARGET_LEVEL_INVALID),
    (False, ("rungs", 0, "protection"), {"ladder": None},
     BassExtensionRefusal.PROTECTION_INVALID),
    (False, ("basis", "bass_fit_sha256"), "nothex",
     BassExtensionRefusal.BASIS_INVALID),
    (False, ("basis", "round_id"), " ", BassExtensionRefusal.BASIS_INVALID),
    # A boosted family is checked against the plant that generated it, and
    # against the protection that measured what it may play.
    (True, ("rungs", 0, "target", "fp_hz"), 46.0,
     BassExtensionRefusal.TARGETS_UNORDERED),
    (True, ("rungs", 0, "target", "filters", 0, "freq_target"), 31.0,
     BassExtensionRefusal.TARGET_INVALID),
    (True, ("rungs", 0, "target", "filters"), [],
     BassExtensionRefusal.TARGET_INVALID),
    (True, ("rungs", 0, "max_level_db"), -3.0,
     BassExtensionRefusal.TARGET_LEVEL_INVALID),
    (True, ("rungs", 0, "protection", "ladder", "verdict"), "fail",
     BassExtensionRefusal.PROTECTION_INVALID),
    (True, ("rungs", 0, "protection", "ladder", "sha256"), "short",
     BassExtensionRefusal.PROTECTION_INVALID),
    # THE hard stop, from both sides: boost with only one evidence attached.
    (True, ("rungs", 0, "protection", "ladder"), None,
     BassExtensionRefusal.PROTECTION_INVALID),
    (True, ("rungs", 0, "protection", "limiter"), None,
     BassExtensionRefusal.PROTECTION_INVALID),
))
def test_each_bound_refuses_under_its_own_name(boosted, path, value, reason):
    with pytest.raises(BassCandidateFieldError) as refusal:
        validate_bass_extension_field(
            _mutate(bass_extension_field(boosted=boosted), path, value)
        )

    assert refusal.value.reason is reason


def test_summary_publishes_the_family_a_household_page_shows():
    summary = bass_extension_summary(bass_extension_field(boosted=True))

    assert summary["commissioned"] is True
    assert summary["adapter_id"] == "sealed_v1"
    assert summary["margin_policy_name"] == MARGIN.name
    assert summary["basis"]["round_id"] == "round-3"
    assert summary["targets"][-1] == {
        "target_id": "natural",
        "fp_hz": PLANT.f0_hz,
        "boost_headroom_db": 0.0,
        "max_level_db": 0.0,
    }


@pytest.mark.parametrize("field", (None, {}, {"owner": "malformed"}))
def test_summary_is_none_for_anything_it_would_refuse(field):
    assert bass_extension_summary(field) is None
