# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Effective speaker-volume facts published to the assistant mix owner.

``VolumeCoordinator`` remains the sole owner of the user's canonical
``listening_level`` and of which physical attenuator carries it. Fan-in needs
one absolute snapshot in order to keep assistant loudness stable across source
handoffs:

* ``canonical_db`` — the calibrated dB representation of user intent;
* ``downstream_db`` — the actual CamillaDSP gain after fan-in.
* ``tts_envelope_lufs`` — the quiet-room speaker target at that intent;
* ``muted`` — the fail-safe final silence assertion;
* ``stamp_boot_ns`` — boot-local ordering bound to snapshot acquisition.

The message is absolute and idempotent. It intentionally contains no source
name or measured-content loudness: source policy and the product's quiet-room
TTS envelope stay in ``VolumeCoordinator``, while content measurement stays in
fan-in.
"""
from __future__ import annotations

import asyncio
import socket
import time
from dataclasses import dataclass
from typing import Awaitable, Callable, Mapping

from .env_load import VOICE_GROUPING_ENV_FILE
from .tts_routing import (
    FANIN_TTS_SOCKET,
    VOICE_TTS_SOCKET_ENV,
    resolve_tts_routing_snapshot,
    resolved_tts_socket_feeds_post_dsp_outputd,
    resolved_tts_socket_feeds_pre_dsp_fanin,
)


@dataclass(frozen=True)
class EffectiveVolumeContext:
    canonical_db: float
    downstream_db: float
    tts_envelope_lufs: float
    muted: bool
    # Bound to the snapshot itself, not generated by a later publisher.  A
    # slow publication of an older snapshot must stay older than a newer one.
    stamp_boot_ns: int


# Returns whether the context reached a consumer: a route whose mix stage is
# unknown is published to nothing, and the caller's telemetry must say so.
VolumeContextPublisher = Callable[[EffectiveVolumeContext], Awaitable[bool]]


def volume_context_stamp_boot_ns() -> int:
    """Timestamp an update in the boot-local clock domain used by fan-in."""
    clock_id = getattr(time, "CLOCK_BOOTTIME", time.CLOCK_MONOTONIC)
    return time.clock_gettime_ns(clock_id)


def serialize_volume_context(context: EffectiveVolumeContext) -> bytes:
    """Serialize the one canonical Python representation of this command."""
    return (
        f"VOLUME_CONTEXT {context.canonical_db:.3f} "
        f"{context.downstream_db:.3f} {context.tts_envelope_lufs:.3f} "
        f"{1 if context.muted else 0} {int(context.stamp_boot_ns)}\n"
    ).encode("ascii")


def _send_volume_context(
    socket_path: str,
    context: EffectiveVolumeContext,
    *,
    timeout: float = 0.5,
) -> None:
    payload = serialize_volume_context(context) + b"CLOSE\n"
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
        sock.settimeout(timeout)
        sock.connect(socket_path)
        sock.sendall(payload)


def _resolved_route_consumes_volume_context(
    resolved: Mapping[str, str],
) -> bool:
    """Whether the resolved TTS route interprets a published VolumeContext.

    Two routes do: the pre-DSP fan-in mix (solo/leader) and the CONFIRMED
    post-DSP outputd mix (a reconciled passive member, since #1547). The SAME
    absolute wire message is sent to whichever socket the route resolved — the
    post-DSP consumer owns the structural fact that its downstream attenuation
    is zero (``downstream_db`` is never mutated to 0 in Python). Unknown stages
    fail closed in both classifiers.
    """
    return (
        resolved_tts_socket_feeds_pre_dsp_fanin(resolved)
        or resolved_tts_socket_feeds_post_dsp_outputd(resolved)
    )


def volume_context_publisher_for_runtime(
    env: Mapping[str, str],
    *,
    grouping_env_path: str | None = VOICE_GROUPING_ENV_FILE,
) -> VolumeContextPublisher:
    """Return a publisher that resolves the TTS route on every publish.

    The route is reconciler-owned state in a ``/var/lib/jasper`` env file that
    changes while these daemons run (a speaker joins or leaves a group), so it
    is read fresh per publish rather than frozen at construction.

    A publish reaches the pre-DSP fan-in mix (solo/leader) or the CONFIRMED
    post-DSP outputd mix (a reconciled passive member); both receive the SAME
    absolute wire message on the socket the route resolved. A route whose mix
    stage is unknown publishes nothing — pre-DSP compensation into an
    uncertain stage can create a large level error.
    """
    process_env = dict(env)

    async def publish(context: EffectiveVolumeContext) -> bool:
        current = resolve_tts_routing_snapshot(
            process_env,
            grouping_env_path=grouping_env_path,
        )
        if not _resolved_route_consumes_volume_context(current):
            return False
        await asyncio.to_thread(
            _send_volume_context,
            current.get(VOICE_TTS_SOCKET_ENV, FANIN_TTS_SOCKET),
            context,
        )
        return True

    return publish
