# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Pure analysis of a crossover excitation-program capture (design §5.6).

``analyze_program_capture(program, samples, sample_rate) -> ProgramAnalysis``
derives segment locations, per-segment integrity, in-capture clock drift,
per-driver gated responses, tweeter-vs-woofer alignment and the crossover
candidate from the ``(program, capture)`` pair alone. No I/O, no product
policy, and no ``jasper.active_speaker`` import
(``tests/test_audio_measurement_boundary_ssot.py`` pins that boundary), so product
crossover transfers arrive as host-evaluated per-role callables on
:class:`MeasurementPriors`.

The analysis is split across this package by phase; the names below are its
public surface, and a test reaches a private helper through its own submodule.
"""

from __future__ import annotations

from jasper.audio_measurement.alignment import parabolic_peak
from jasper.audio_measurement.excitation import DECONV_PRE_GUARD_S
from jasper.audio_measurement.program import KIND_SWEEP
from .model import (
    ALIGNMENT_ESTIMATED_FLAT_SUM,
    ALIGNMENT_DELAY_EXCEEDS_SEARCH_WINDOW,
    ALIGNMENT_FLAT_MINIMUM_EPSILON_DB,
    ALIGNMENT_FLATNESS_MAX_STEPS,
    ALIGNMENT_FLATNESS_STEP_US,
    ALIGNMENT_OK,
    ALIGNMENT_SNR_REFUSAL_VERDICT,
    AlignmentEstimate,
    AMBIENT_NONSTATIONARITY_DB,
    ANCHOR_DISCRIMINATION_RATIO,
    AppliedAlignment,
    CAPTURE_BOUND_MARGIN_S,
    CaptureIntegrity,
    CHANNEL_MAP_MIN_ISOLATION_DB,
    CHANNEL_MAP_TARGET_RISE_DB,
    DELTA_IMPLAUSIBLE_GAP_DB,
    ConfiguredPathConditioningError,
    CrossoverCandidate,
    DISCONTINUITY_UNRESOLVED,
    DriftEstimate,
    DRIVER_SNR_ALIGNMENT_KEY,
    DriverResponse,
    GAIN_BOUND_CAPTURE_FLOOR,
    GAIN_BOUND_DEGENERATE_AMBIENT,
    GAIN_BOUND_FLAT_TARGET,
    GAIN_BOUND_NO_AMBIENT_EVIDENCE,
    GAIN_BOUND_PILOT_SNR,
    GAIN_BOUND_ROOM_SNR,
    GAIN_BOUNDS,
    GAIN_MAX_DIGITAL_PEAK_DBFS,
    GainPlan,
    GCC_SNAP_RADIUS_PERIODS,
    GLITCH_RESIDUAL_SAMPLES,
    ILL_CONDITIONED_PROTECTION_DEEMBEDDING,
    INTEGRITY_CHECK_CLIPPED_RUN,
    INTEGRITY_CHECK_DISCONTINUITY_STEP,
    INTEGRITY_CHECK_FRAME_LEDGER,
    INTEGRITY_CHECK_CAPTURE_OVERRUN,
    INTEGRITY_CHECK_REPEAT_EPSILON,
    INTEGRITY_CHECK_SWEEP_HEARD,
    INTEGRITY_CHECK_SWEEP_SCHEDULE,
    INTEGRITY_CHECK_WITHIN_ROLE_DESYNC,
    INTEGRITY_FAIL,
    INTEGRITY_NOT_EVALUATED,
    INTEGRITY_PASS,
    IntegrityCheck,
    IR_POST_MS,
    IR_PRE_MS,
    LINEARITY_SNR_BIAS_BUDGET_FRACTION,
    LINEARITY_TOLERANCE_DB,
    LOCATOR_RATE_HZ,
    MAX_DRIFT_PPM,
    MEASURE_SNR_SOLVE_MARGIN_DB,
    MeasurementGeometry,
    MeasurementPriors,
    PILOT_MIN_SNR_DB,
    PilotObservation,
    ProgramAnalysis,
    REALIZED_LEVEL_MATCH_TOLERANCE_DB,
    RecordedImpulse,
    RIPPLE_TRIM_FLAT_MINIMUM_EPSILON_DB,
    RIPPLE_TRIM_MAX_DB,
    RIPPLE_TRIM_SEARCH_STEP_DB,
    RIPPLE_TRIM_SEARCH_WINDOW_DB,
    RoleGainSolve,
    SEGMENT_SEARCH_S,
    SegmentLocation,
    sweep_band_crest_factor_db,
    SWEEP_LOCATE_CONFIDENCE_FLOOR,
    SWEEP_PEAK_TO_RMS_DB,
    SWEEP_SCHEDULE_RESIDUAL_CEILING_MS,
    VERIFY_NOTCH_EXCLUSION_DB,
    VERIFY_TRACKING_SMOOTHING_FRACTION,
)
from .locate import locate_global_offset, locate_segments
from .drift import estimate_drift
from .response import (
    branch_level_bands_hz,
    deconvolve_window,
    driver_response,
    half_period_us,
    n_fft_for,
    polarity_label,
    predicted_branch_sum,
    recorded_impulse,
    ripple_at_trim,
    solve_branch_trims,
    solve_ripple_optimal_trim,
    summed_model_residual_delay_us,
)
from .check import (
    AMBIENT_MIN_USABLE_FRACTION,
    ambient_rows_in_band,
    channel_map_isolation_db,
    clears_snr_floor,
)
from .dispatch import (
    ABSOLUTE_NO_CROSSOVER_TOPOLOGY,
    ABSOLUTE_NO_FC,
    ABSOLUTE_NO_TARGET,
    ABSOLUTE_NO_TRUSTED_BAND,
    analyze_program_capture,
    MEASURE_PAIR_SINGLE_DRIVER,
)
from .summary import (
    analysis_diagnostic_summary,
    driver_alignment_snr_verdict,
    driver_snr_verdict,
)

__all__ = [
    "ABSOLUTE_NO_CROSSOVER_TOPOLOGY",
    "ABSOLUTE_NO_FC",
    "ABSOLUTE_NO_TARGET",
    "ABSOLUTE_NO_TRUSTED_BAND",
    "ALIGNMENT_ESTIMATED_FLAT_SUM",
    "ALIGNMENT_DELAY_EXCEEDS_SEARCH_WINDOW",
    "ALIGNMENT_FLAT_MINIMUM_EPSILON_DB",
    "ALIGNMENT_FLATNESS_MAX_STEPS",
    "ALIGNMENT_FLATNESS_STEP_US",
    "ALIGNMENT_OK",
    "ALIGNMENT_SNR_REFUSAL_VERDICT",
    "AlignmentEstimate",
    "AMBIENT_MIN_USABLE_FRACTION",
    "AMBIENT_NONSTATIONARITY_DB",
    "ambient_rows_in_band",
    "analysis_diagnostic_summary",
    "analyze_program_capture",
    "ANCHOR_DISCRIMINATION_RATIO",
    "AppliedAlignment",
    "branch_level_bands_hz",
    "CAPTURE_BOUND_MARGIN_S",
    "CaptureIntegrity",
    "channel_map_isolation_db",
    "CHANNEL_MAP_MIN_ISOLATION_DB",
    "CHANNEL_MAP_TARGET_RISE_DB",
    "clears_snr_floor",
    "DELTA_IMPLAUSIBLE_GAP_DB",
    "ConfiguredPathConditioningError",
    "CrossoverCandidate",
    "DECONV_PRE_GUARD_S",
    "deconvolve_window",
    "DISCONTINUITY_UNRESOLVED",
    "DriftEstimate",
    "driver_alignment_snr_verdict",
    "driver_response",
    "DRIVER_SNR_ALIGNMENT_KEY",
    "driver_snr_verdict",
    "DriverResponse",
    "estimate_drift",
    "GAIN_BOUND_CAPTURE_FLOOR",
    "GAIN_BOUND_DEGENERATE_AMBIENT",
    "GAIN_BOUND_FLAT_TARGET",
    "GAIN_BOUND_NO_AMBIENT_EVIDENCE",
    "GAIN_BOUND_PILOT_SNR",
    "GAIN_BOUND_ROOM_SNR",
    "GAIN_BOUNDS",
    "GAIN_MAX_DIGITAL_PEAK_DBFS",
    "GainPlan",
    "GCC_SNAP_RADIUS_PERIODS",
    "GLITCH_RESIDUAL_SAMPLES",
    "half_period_us",
    "ILL_CONDITIONED_PROTECTION_DEEMBEDDING",
    "INTEGRITY_CHECK_CLIPPED_RUN",
    "INTEGRITY_CHECK_DISCONTINUITY_STEP",
    "INTEGRITY_CHECK_FRAME_LEDGER",
    "INTEGRITY_CHECK_CAPTURE_OVERRUN",
    "INTEGRITY_CHECK_REPEAT_EPSILON",
    "INTEGRITY_CHECK_SWEEP_HEARD",
    "INTEGRITY_CHECK_SWEEP_SCHEDULE",
    "INTEGRITY_CHECK_WITHIN_ROLE_DESYNC",
    "INTEGRITY_FAIL",
    "INTEGRITY_NOT_EVALUATED",
    "INTEGRITY_PASS",
    "IntegrityCheck",
    "IR_POST_MS",
    "IR_PRE_MS",
    "KIND_SWEEP",
    "LINEARITY_SNR_BIAS_BUDGET_FRACTION",
    "LINEARITY_TOLERANCE_DB",
    "locate_global_offset",
    "locate_segments",
    "LOCATOR_RATE_HZ",
    "MAX_DRIFT_PPM",
    "MEASURE_PAIR_SINGLE_DRIVER",
    "MEASURE_SNR_SOLVE_MARGIN_DB",
    "MeasurementGeometry",
    "MeasurementPriors",
    "n_fft_for",
    "parabolic_peak",
    "PILOT_MIN_SNR_DB",
    "PilotObservation",
    "polarity_label",
    "predicted_branch_sum",
    "ProgramAnalysis",
    "REALIZED_LEVEL_MATCH_TOLERANCE_DB",
    "RecordedImpulse",
    "recorded_impulse",
    "ripple_at_trim",
    "RIPPLE_TRIM_FLAT_MINIMUM_EPSILON_DB",
    "RIPPLE_TRIM_MAX_DB",
    "RIPPLE_TRIM_SEARCH_STEP_DB",
    "RIPPLE_TRIM_SEARCH_WINDOW_DB",
    "RoleGainSolve",
    "SEGMENT_SEARCH_S",
    "SegmentLocation",
    "solve_branch_trims",
    "solve_ripple_optimal_trim",
    "summed_model_residual_delay_us",
    "sweep_band_crest_factor_db",
    "SWEEP_LOCATE_CONFIDENCE_FLOOR",
    "SWEEP_PEAK_TO_RMS_DB",
    "SWEEP_SCHEDULE_RESIDUAL_CEILING_MS",
    "VERIFY_NOTCH_EXCLUSION_DB",
    "VERIFY_TRACKING_SMOOTHING_FRACTION",
]
