# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Pure analysis of a crossover excitation-program capture (design §5.6).

``analyze_program_capture(program, samples, sample_rate) -> ProgramAnalysis``
derives segment locations, per-segment integrity, in-capture clock drift,
per-driver gated responses, tweeter-vs-woofer alignment and the crossover
candidate from the ``(program, capture)`` pair alone. No I/O, no product
policy, and no ``jasper.correction`` / ``jasper.active_speaker`` import
(``tests/test_correction_boundary_ssot.py`` pins that boundary), so product
crossover transfers arrive as host-evaluated per-role callables on
:class:`MeasurementPriors`.

The analysis is split across this package by phase; the names below are the
surface every importer outside it uses.
"""

from __future__ import annotations

from jasper.audio_measurement.alignment import parabolic_peak
from jasper.audio_measurement.program import KIND_SWEEP
from .model import (
    ALIGNMENT_COMMITMENTS,
    ALIGNMENT_COMMITTED_APPLIED_HELD_AFTER_LOW_SNR,
    ALIGNMENT_COMMITTED_DECLARED_AFTER_LOW_SNR,
    ALIGNMENT_COMMITTED_EXPLICIT_AFTER_LOW_SNR,
    ALIGNMENT_COMMITTED_EXPLICIT_PRESCRIPTION,
    ALIGNMENT_COMMITTED_FLAT_SUM,
    ALIGNMENT_COMMITTED_NONE_AFTER_UNREADABLE_APPLY,
    ALIGNMENT_COMMITTED_SEED_NO_SCORING_BAND,
    ALIGNMENT_DECLARED_POLARITY_OBJECTIVES,
    ALIGNMENT_DELAY_EXCEEDS_SEARCH_WINDOW,
    ALIGNMENT_EXPLICIT_PRESCRIPTION_OBJECTIVES,
    ALIGNMENT_FLAT_MINIMUM_EPSILON_DB,
    ALIGNMENT_FLATNESS_MAX_STEPS,
    ALIGNMENT_FLATNESS_STEP_US,
    ALIGNMENT_OK,
    ALIGNMENT_SNR_REFUSAL_VERDICT,
    AlignmentEstimate,
    AMBIENT_NONSTATIONARITY_DB,
    ANCHOR_DISCRIMINATION_RATIO,
    AppliedAlignment,
    CAPTURE_BOUND_MARGIN_S,
    CaptureIntegrity,
    CHANNEL_MAP_ISOLATION_JUDGED_ABOVE_DB,
    CHANNEL_MAP_MIN_ISOLATION_DB,
    CHANNEL_MAP_TARGET_RISE_DB,
    ConfiguredPathConditioningError,
    CrossoverCandidate,
    DECONV_PRE_GUARD_S,
    DISCONTINUITY_UNRESOLVED,
    DriftEstimate,
    DRIVER_SNR_ALIGNMENT_KEY,
    DriverResponse,
    GAIN_BOUND_CAPTURE_FLOOR,
    GAIN_BOUND_DEGENERATE_AMBIENT,
    GAIN_BOUND_FLAT_TARGET,
    GAIN_BOUND_NO_AMBIENT_EVIDENCE,
    GAIN_BOUND_PILOT_SNR,
    GAIN_BOUND_ROOM_SNR,
    GAIN_BOUNDS,
    GAIN_MAX_DIGITAL_PEAK_DBFS,
    GainPlan,
    GCC_SNAP_RADIUS_PERIODS,
    GLITCH_RESIDUAL_SAMPLES,
    ILL_CONDITIONED_PROTECTION_DEEMBEDDING,
    INTEGRITY_CHECK_CLIPPED_RUN,
    INTEGRITY_CHECK_DISCONTINUITY_STEP,
    INTEGRITY_CHECK_FRAME_LEDGER,
    INTEGRITY_CHECK_RENDER_GAP,
    INTEGRITY_CHECK_REPEAT_EPSILON,
    INTEGRITY_CHECK_REPEAT_LEVEL,
    INTEGRITY_CHECK_SWEEP_HEARD,
    INTEGRITY_CHECK_SWEEP_SCHEDULE,
    INTEGRITY_CHECK_WITHIN_ROLE_DESYNC,
    INTEGRITY_FAIL,
    INTEGRITY_NOT_EVALUATED,
    INTEGRITY_PASS,
    IntegrityCheck,
    IR_POST_MS,
    IR_PRE_MS,
    LINEARITY_SNR_BIAS_BUDGET_FRACTION,
    LINEARITY_TOLERANCE_DB,
    LOCATOR_RATE_HZ,
    MAX_DRIFT_PPM,
    MEASURE_SNR_SOLVE_MARGIN_DB,
    MeasurementGeometry,
    MeasurementPriors,
    PILOT_MIN_SNR_DB,
    PilotObservation,
    ProgramAnalysis,
    REALIZED_LEVEL_MATCH_TOLERANCE_DB,
    REPEAT_LEVEL_TOLERANCE_DB,
    RIPPLE_TRIM_FLAT_MINIMUM_EPSILON_DB,
    RIPPLE_TRIM_MAX_DB,
    RIPPLE_TRIM_MIN_DB,
    RIPPLE_TRIM_SEARCH_STEP_DB,
    RIPPLE_TRIM_SEARCH_WINDOW_DB,
    RoleGainSolve,
    SEGMENT_SEARCH_S,
    SegmentLocation,
    sweep_band_crest_factor_db,
    SWEEP_LOCATE_CONFIDENCE_FLOOR,
    SWEEP_PEAK_TO_RMS_DB,
    SWEEP_SCHEDULE_RESIDUAL_CEILING_MS,
    VERIFY_NOTCH_EXCLUSION_DB,
    VERIFY_TRACKING_SMOOTHING_FRACTION,
)
from .signals import _band_average_db, _complex_tf, _peak_dbfs
from .locate import (
    _earliest_strong_peak,
    _global_offset,
    _locate_in_window,
    _locate_segments,
    _stimulus_shape,
)
from .drift import _estimate_drift, _locate_discontinuity, _sweep_occurrence_index
from .verify_integrity import _verify_capture_integrity
from .response import (
    _aligned_branch_tf,
    branch_level_bands_hz,
    _deconvolve_window,
    _driver_response,
    _gate_floor_hz,
    half_period_us,
    _n_fft_for,
    polarity_label,
    predicted_branch_sum,
    _raw_sweep_segment,
    realized_branch_level_match,
    RealizedLevelMatch,
    ripple_at_trim,
    _ripple_db,
    _select_alignment_pair,
    solve_branch_trims,
    solve_ripple_optimal_trim,
    summed_model_residual_delay_us,
)
from .check import (
    _aggregate_linearity_ok,
    _aggregate_tri_state_ok,
    _ambient_from_capture,
    AMBIENT_MIN_USABLE_FRACTION,
    _ambient_rows_in_band,
    _band_exclusive_pieces,
    _band_rms_dbfs,
    channel_map_isolation_db,
    _channel_map_ok,
    _pilot_ambient_samples,
    _snr_floor_ok,
    _solve_gain_plan,
)
from .dispatch import (
    ABSOLUTE_NO_CROSSOVER_TOPOLOGY,
    ABSOLUTE_NO_FC,
    ABSOLUTE_NO_TARGET,
    ABSOLUTE_NO_TRUSTED_BAND,
    analyze_program_capture,
    _build_candidate,
    _compose_configured_path_ir,
    MEASURE_PAIR_SINGLE_DRIVER,
)
from .summary import (
    analysis_diagnostic_summary,
    driver_alignment_snr_verdict,
    driver_snr_verdict,
)

__all__ = [
    "ABSOLUTE_NO_CROSSOVER_TOPOLOGY",
    "ABSOLUTE_NO_FC",
    "ABSOLUTE_NO_TARGET",
    "ABSOLUTE_NO_TRUSTED_BAND",
    "_aggregate_linearity_ok",
    "_aggregate_tri_state_ok",
    "_aligned_branch_tf",
    "ALIGNMENT_COMMITMENTS",
    "ALIGNMENT_COMMITTED_APPLIED_HELD_AFTER_LOW_SNR",
    "ALIGNMENT_COMMITTED_DECLARED_AFTER_LOW_SNR",
    "ALIGNMENT_COMMITTED_EXPLICIT_AFTER_LOW_SNR",
    "ALIGNMENT_COMMITTED_EXPLICIT_PRESCRIPTION",
    "ALIGNMENT_COMMITTED_FLAT_SUM",
    "ALIGNMENT_COMMITTED_NONE_AFTER_UNREADABLE_APPLY",
    "ALIGNMENT_COMMITTED_SEED_NO_SCORING_BAND",
    "ALIGNMENT_DECLARED_POLARITY_OBJECTIVES",
    "ALIGNMENT_DELAY_EXCEEDS_SEARCH_WINDOW",
    "ALIGNMENT_EXPLICIT_PRESCRIPTION_OBJECTIVES",
    "ALIGNMENT_FLAT_MINIMUM_EPSILON_DB",
    "ALIGNMENT_FLATNESS_MAX_STEPS",
    "ALIGNMENT_FLATNESS_STEP_US",
    "ALIGNMENT_OK",
    "ALIGNMENT_SNR_REFUSAL_VERDICT",
    "AlignmentEstimate",
    "_ambient_from_capture",
    "AMBIENT_MIN_USABLE_FRACTION",
    "AMBIENT_NONSTATIONARITY_DB",
    "_ambient_rows_in_band",
    "analysis_diagnostic_summary",
    "analyze_program_capture",
    "ANCHOR_DISCRIMINATION_RATIO",
    "AppliedAlignment",
    "_band_average_db",
    "_band_exclusive_pieces",
    "_band_rms_dbfs",
    "branch_level_bands_hz",
    "_build_candidate",
    "CAPTURE_BOUND_MARGIN_S",
    "CaptureIntegrity",
    "channel_map_isolation_db",
    "CHANNEL_MAP_ISOLATION_JUDGED_ABOVE_DB",
    "CHANNEL_MAP_MIN_ISOLATION_DB",
    "_channel_map_ok",
    "CHANNEL_MAP_TARGET_RISE_DB",
    "_complex_tf",
    "_compose_configured_path_ir",
    "ConfiguredPathConditioningError",
    "CrossoverCandidate",
    "DECONV_PRE_GUARD_S",
    "_deconvolve_window",
    "DISCONTINUITY_UNRESOLVED",
    "DriftEstimate",
    "driver_alignment_snr_verdict",
    "_driver_response",
    "DRIVER_SNR_ALIGNMENT_KEY",
    "driver_snr_verdict",
    "DriverResponse",
    "_earliest_strong_peak",
    "_estimate_drift",
    "GAIN_BOUND_CAPTURE_FLOOR",
    "GAIN_BOUND_DEGENERATE_AMBIENT",
    "GAIN_BOUND_FLAT_TARGET",
    "GAIN_BOUND_NO_AMBIENT_EVIDENCE",
    "GAIN_BOUND_PILOT_SNR",
    "GAIN_BOUND_ROOM_SNR",
    "GAIN_BOUNDS",
    "GAIN_MAX_DIGITAL_PEAK_DBFS",
    "GainPlan",
    "_gate_floor_hz",
    "GCC_SNAP_RADIUS_PERIODS",
    "GLITCH_RESIDUAL_SAMPLES",
    "_global_offset",
    "half_period_us",
    "ILL_CONDITIONED_PROTECTION_DEEMBEDDING",
    "INTEGRITY_CHECK_CLIPPED_RUN",
    "INTEGRITY_CHECK_DISCONTINUITY_STEP",
    "INTEGRITY_CHECK_FRAME_LEDGER",
    "INTEGRITY_CHECK_RENDER_GAP",
    "INTEGRITY_CHECK_REPEAT_EPSILON",
    "INTEGRITY_CHECK_REPEAT_LEVEL",
    "INTEGRITY_CHECK_SWEEP_HEARD",
    "INTEGRITY_CHECK_SWEEP_SCHEDULE",
    "INTEGRITY_CHECK_WITHIN_ROLE_DESYNC",
    "INTEGRITY_FAIL",
    "INTEGRITY_NOT_EVALUATED",
    "INTEGRITY_PASS",
    "IntegrityCheck",
    "IR_POST_MS",
    "IR_PRE_MS",
    "KIND_SWEEP",
    "LINEARITY_SNR_BIAS_BUDGET_FRACTION",
    "LINEARITY_TOLERANCE_DB",
    "_locate_discontinuity",
    "_locate_in_window",
    "_locate_segments",
    "LOCATOR_RATE_HZ",
    "MAX_DRIFT_PPM",
    "MEASURE_PAIR_SINGLE_DRIVER",
    "MEASURE_SNR_SOLVE_MARGIN_DB",
    "MeasurementGeometry",
    "MeasurementPriors",
    "_n_fft_for",
    "parabolic_peak",
    "_peak_dbfs",
    "_pilot_ambient_samples",
    "PILOT_MIN_SNR_DB",
    "PilotObservation",
    "polarity_label",
    "predicted_branch_sum",
    "ProgramAnalysis",
    "_raw_sweep_segment",
    "realized_branch_level_match",
    "REALIZED_LEVEL_MATCH_TOLERANCE_DB",
    "RealizedLevelMatch",
    "REPEAT_LEVEL_TOLERANCE_DB",
    "ripple_at_trim",
    "_ripple_db",
    "RIPPLE_TRIM_FLAT_MINIMUM_EPSILON_DB",
    "RIPPLE_TRIM_MAX_DB",
    "RIPPLE_TRIM_MIN_DB",
    "RIPPLE_TRIM_SEARCH_STEP_DB",
    "RIPPLE_TRIM_SEARCH_WINDOW_DB",
    "RoleGainSolve",
    "SEGMENT_SEARCH_S",
    "SegmentLocation",
    "_select_alignment_pair",
    "_snr_floor_ok",
    "solve_branch_trims",
    "_solve_gain_plan",
    "solve_ripple_optimal_trim",
    "_stimulus_shape",
    "summed_model_residual_delay_us",
    "sweep_band_crest_factor_db",
    "SWEEP_LOCATE_CONFIDENCE_FLOOR",
    "_sweep_occurrence_index",
    "SWEEP_PEAK_TO_RMS_DB",
    "SWEEP_SCHEDULE_RESIDUAL_CEILING_MS",
    "_verify_capture_integrity",
    "VERIFY_NOTCH_EXCLUSION_DB",
    "VERIFY_TRACKING_SMOOTHING_FRACTION",
]
