# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Explicit foreground commissioning for managed XVF3800 chip AEC."""

from __future__ import annotations

import argparse
import asyncio
import logging
import os
import shutil
import signal
import subprocess
import sys
import tempfile
import threading
import time
import wave
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from types import FrameType
from typing import Any, TypeVar

import numpy as np

from jasper.active_speaker.calibration_level import AUDIBLE_RAMP_STEP_DB
from jasper.active_speaker.volume_latch import fader_matches
from jasper.atomic_io import atomic_write_json
from jasper.audio_hardware import dac as dac_registry
from jasper.audio_measurement.correction_lane import run_correction_play
from jasper.camilla import (
    MAIN_VOLUME_RAMP_SETTLE_S,
    declare_main_volume_db,
    read_main_volume_db,
)
from jasper.chip_aec.alignment import (
    ARTIFACT_PATH,
    AlignmentArtifact,
    LevelProbe,
    MAX_CENTER_ERROR,
    MIN_EDGE_MARGIN,
    MIC_COUNT,
    MicTiming,
    PLAYBACK_RATE,
    ProductResult,
    Rejected,
    TIMING_TRIALS,
    analyze_level,
    analyze_product,
    analyze_timing,
    choose_delay,
    commissioning_stimulus,
    dbfs_rms,
    load_artifact,
    median_samples,
    read_capture,
    WINDOW_CENTER,
)
from jasper.chip_aec.record import (
    CommissionOutcome,
    OUTCOME_PATH,
    write as write_outcome_record,
)
from jasper.chip_aec.policy import STATUS_APPROVED, static_dac_qualification
from jasper.chip_aec.shipped import render_entry
from jasper.cli import aec_init
from jasper.correction.coordinator import (
    HeldWindow,
    MEASUREMENT_GATE_COMMAND_TIMEOUT_SEC,
    MEASUREMENT_HOLD_COMMAND_TIMEOUT_SEC,
)
from jasper.env_load import merged_env_files
from jasper.log_event import log_event
from jasper.mics import xvf3800

logger = logging.getLogger("jasper.aec_commission")
_T = TypeVar("_T")
MARKER = Path("/run/jasper-chip-aec-commission/active")
# Where a rejected run's captures land instead of unwinding with the temp
# dir, and how many rejections are kept.  Three is the run of rejections the
# owner already has (#3271); a run retains two timing phases x MIC_COUNT x
# TIMING_TRIALS files plus the product pair and the warm-up level probe, each
# CAPTURE_SECONDS x 6 ch x 16 kHz S16 (~0.4 MB), so the ceiling is single-digit
# MB of /var/lib.
REJECTED_CAPTURE_DIR = Path("/var/lib/jasper/chip-aec-rejections")
RETAINED_REJECTIONS = 3
# Never the stimulus or adaptation train the same run writes: both are
# regenerated byte-for-byte from `commissioning_stimulus`, and the adaptation
# train alone is 17 MB.  The warm-up CAPTURE is kept — it is the level probe's
# only evidence.
WARMUP_CAPTURE_NAME = "level-warmup.wav"
REJECTED_CAPTURE_GLOBS = ("*-m*-*.wav", "aec-o*.wav", WARMUP_CAPTURE_NAME)
# Reason literal that routes deploy/bin/jasper-aec-reconcile into its
# arm-only dispatch while this process's marker is live; every other reason
# under a live marker is a mutate-nothing no-op there.
ARM_RECONCILE_REASON = "chip-aec-commission-arm"
_CLEANUP_RECONCILE_REASON = "chip-aec-commission"
# This run's identity on mux's diagnostic gate; mux.FANIN_TEST_OWNERS is a
# closed allowlist, so the two literals must stay in step.
COMMISSION_GATE_OWNER = "chip-aec-commission"
# Ceiling on the window's teardown, derived from the ladder it actually runs:
# three mux TEST_RELEASE attempts, then one jasper-control release. Doubled for
# the inter-attempt back-offs and the loop's own shutdown. Reaching it means a
# wedged socket, not a slow one, so the join is abandoned with an event rather
# than parking the CLI; mux's FANIN_TEST_LEASE_SEC then reopens music itself.
ISOLATION_RELEASE_TIMEOUT_SEC = 2 * (
    3 * MEASUREMENT_GATE_COMMAND_TIMEOUT_SEC + MEASUREMENT_HOLD_COMMAND_TIMEOUT_SEC
)
MEASUREMENT_VOLUME_DB = -28.282827
INITIAL_SYS_DELAY = xvf3800.CHIP_AEC_SYS_DELAY_DEFAULT
# The audible budget.  A capture is audible for its whole `arecord -d` window
# whatever fraction of it the sweep occupies, plus the lead before playback
# starts; adaptation is audible for the chunks it plays and stops early on the
# chip's own AEC_AECCONVERGED.  `chirp_seconds` holds the plan to the cap.
CAPTURE_SECONDS = 2
CAPTURE_LEAD_SECONDS = 0.25
# One chunk is one copy of the padded stimulus.  The guards are load-bearing
# for the chip, not just for the capture analysis: back-to-back sweep copies
# are periodic far-end and the AEC never converged on them (62 s), while the
# gapped train converged at copy 34.
ADAPTATION_CHUNKS = 60
# The worst case the plan above can actually cost, not a target: the run is
# dominated by adaptation at the present too-quiet stimulus level.  Bringing it
# toward 30 s is the auto-level follow-up's job (a louder stimulus converges
# sooner) and, failing that, continuous-noise adaptation.
CHIRP_BUDGET_SECONDS = 85.0
STOP_UNITS = (
    "jasper-voice.service",
    "jasper-aec-bridge.service",
    "jasper-aec-init.service",
    "jasper-outputd.service",
)


class CommissioningError(RuntimeError):
    pass


@dataclass(frozen=True)
class Hardware:
    variant: str
    card: str
    plan: xvf3800.ChipBeamPlan


@dataclass(frozen=True)
class QueueWindow:
    status: Mapping[str, Any]
    samples: tuple[int, ...]


class IsolationLease:
    """Run a :class:`HeldWindow` on a dedicated thread and its own loop.

    Inverted relative to ``doctor.aec_probe``, which keeps the window on the
    main loop and pushes its body to ``asyncio.to_thread``: a signal unwinds
    only the MAIN thread, and commissioning's body is the half that must
    unwind — its ``finally`` restores the household fader and closes the chip.
    So the body stays put and the window moves.
    """

    def __init__(self, gate_owner: str) -> None:
        self.gate_owner = gate_owner
        #: The one failure this lease produced, set on the way out.
        self.error: BaseException | None = None
        # skip_voice_pause: STOP_UNITS stops jasper-voice outright moments
        # after this window opens, so there is no daemon left to MEASURE_PAUSE
        # or to RESUME. That also skips PAUSE's proof that prior assistant
        # audio drained; the XVF reset and the arm reconcile between the stop
        # and the first capture cover that gap.
        self._window = HeldWindow(gate_owner=gate_owner, skip_voice_pause=True)
        self._thread = threading.Thread(
            target=lambda: asyncio.run(self._window.hold()),
            name="chip-aec-isolation",
            daemon=True,
        )

    @property
    def lost(self) -> threading.Event:
        return self._window.lost

    def check(self) -> None:
        """Refuse work whose audio would carry the household's."""

        if self._window.lost.is_set():
            raise CommissioningError("household audio isolation was lost mid-run")

    def start(self) -> None:
        """Block until the gate is held, or raise the entry failure here."""

        self._thread.start()
        self._window.entered.wait()
        if not self._window.held and self._window.error is not None:
            raise self._window.error

    def stop(self) -> None:
        """Leave the window and join. Never replaces the run's own verdict."""

        try:
            self._window.release()
            self._thread.join(ISOLATION_RELEASE_TIMEOUT_SEC)
            if self._thread.is_alive():
                self.error = TimeoutError(
                    "isolation release did not finish in "
                    f"{ISOLATION_RELEASE_TIMEOUT_SEC}s"
                )
        except CommissioningError as exc:
            # A second SIGTERM lands here as `_signal`'s exception. The run
            # already has its verdict; keep this as a release failure instead
            # of letting it replace that verdict on the way out.
            self.error = exc
        self.error = self.error or self._window.error
        if self.error is not None and not self._window.lost.is_set():
            # Its own event, never the run's verdict: a release that did not
            # land leaves music gated until mux's lease lapses, which the
            # operator has to see even when the sweep itself passed.
            log_event(
                logger,
                "chip_aec_commission.isolation_release_failed",
                owner=self.gate_owner,
                error=str(self.error),
                level=logging.ERROR,
            )


def _run(command: Sequence[str], *, timeout: float = 30) -> None:
    result = subprocess.run(
        list(command), capture_output=True, text=True, timeout=timeout
    )
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        raise CommissioningError(f"{' '.join(command)}: {detail}")


def _play_correction(wav: Path, *, timeout: float) -> None:
    """Correction-lane playback with this CLI's error policy.

    The spawn (argv, captured text output, and the lane umask) is the shared
    helper's since P6c-i; what stays HERE is commissioning's own contract —
    a nonzero exit becomes ``CommissioningError`` with the same
    ``"<argv joined>: <detail>"`` message ``_run`` produces for every other
    command this CLI shells out to.
    """
    result = run_correction_play(wav, timeout=timeout)
    if result.returncode:
        detail = (result.stderr or result.stdout).strip()
        raise CommissioningError(f"{' '.join(result.args)}: {detail}")


def _create_marker(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_NOFOLLOW", 0)
    try:
        fd = os.open(path, flags, 0o644)
    except FileExistsError as exc:
        raise CommissioningError(f"commissioning is already active: {path}") from exc
    try:
        os.write(fd, f"pid={os.getpid()}\n".encode())
        os.fsync(fd)
    finally:
        os.close(fd)


def chirp_seconds(stimulus_frames: int) -> float:
    """Seconds a full run is audible at worst: warmup, both timing phases, the
    AEC-on/AEC-off pair, and every adaptation chunk the cap allows."""

    captures = 1 + 2 * MIC_COUNT * TIMING_TRIALS + 2
    return captures * (CAPTURE_SECONDS + CAPTURE_LEAD_SECONDS) + (
        ADAPTATION_CHUNKS * stimulus_frames / PLAYBACK_RATE
    )


def _final_timing(evidence: Sequence[MicTiming]) -> tuple[tuple[int, ...], float, int]:
    lags = tuple(item.lag for item in evidence)
    center = (min(lags) + max(lags)) / 2
    margin = min(
        min(
            item.lag - xvf3800.CHIP_AEC_FIRST_PEAK_HARD_MIN,
            xvf3800.CHIP_AEC_FIRST_PEAK_HARD_MAX - item.lag,
        )
        for item in evidence
    )
    if margin < MIN_EDGE_MARGIN:
        raise CommissioningError(f"final causal-window margin is only {margin} samples")
    if abs(center - WINDOW_CENTER) > MAX_CENTER_ERROR:
        raise CommissioningError(f"final causal-window center is {center:.1f} samples")
    return lags, center, margin


def _retain_rejected_captures(directory: Path, root: Path) -> Path | None:
    """Move a rejected run's timing and product captures out of the temp dir.

    Best-effort: a retention failure must not replace the rejection the owner
    actually needs to read.
    """

    destination = root / time.strftime("%Y%m%dT%H%M%SZ", time.gmtime())
    moved = 0
    try:
        captures = sorted(
            capture
            for pattern in REJECTED_CAPTURE_GLOBS
            for capture in directory.glob(pattern)
        )
        if not captures:
            return None
        destination.mkdir(parents=True, exist_ok=True)
        for capture in captures:
            shutil.move(capture, destination / capture.name)
            moved += 1
        # Never a prune candidate: the box has no RTC, so a restored or stepped
        # clock can name this run older than the ones it joins.
        stale = sorted(
            (path for path in root.iterdir() if path.is_dir() and path != destination),
            reverse=True,
        )
        for path in stale[RETAINED_REJECTIONS - 1 :]:
            shutil.rmtree(path, ignore_errors=True)
    except OSError as exc:
        log_event(
            logger,
            "chip_aec_commission.retain_failed",
            error=str(exc),
            moved=moved,
            level=logging.WARNING,
        )
    return destination if moved else None


def _guarded(
    call: Callable[[], _T], directory: Path, rejection_dir: Path,
    *, lease: IsolationLease, gate: str, phase: str = "",
) -> _T:
    """Every analyzer ValueError lands here, not only the gate verdicts: a
    refusal carrying no fields is the one whose captures matter most."""

    phase = phase or gate
    lease.check()
    try:
        return call()
    except ValueError as rejection:
        retained = _retain_rejected_captures(directory, rejection_dir)
        log_event(
            logger,
            f"chip_aec_commission.{gate}_rejected",
            phase=phase,
            retained_captures=retained,
            **getattr(rejection, "fields", {}),
            level=logging.ERROR,
        )
        raise CommissioningError(
            f"{rejection} phase={phase} retained_captures={retained}"
        ) from rejection


def _auto_level(
    io, hardware: Hardware, stimulus: Path, active: np.ndarray, directory: Path,
    lease: IsolationLease,
) -> dict[str, Any]:
    """Set the run's measurement level once, from the warm-up capture.

    `MEASUREMENT_VOLUME_DB` is the level the probe is TAKEN at, not the level
    the run measures at.  There is no second probe, so a room a whole audible
    step or more from the target is refused rather than under-shot.
    """

    probe = io.warmup(hardware, stimulus, active, directory, lease)
    offset = probe.offset_db(AUDIBLE_RAMP_STEP_DB)
    volume = MEASUREMENT_VOLUME_DB + offset
    record = {
        **probe.evidence(),
        "level_offset_db": round(offset, 2),
        "selected_volume_db": round(volume, 2),
    }
    if not probe.reaches_target(AUDIBLE_RAMP_STEP_DB):
        raise Rejected("level", {**record, "step_cap_db": AUDIBLE_RAMP_STEP_DB})
    io.set_volume(volume)
    return record


def _timing_trials(
    io, dev, hardware: Hardware, delay: int, stimulus: Path,
    reference: np.ndarray, directory: Path, label: str, lease: IsolationLease,
) -> tuple[MicTiming, ...]:
    return tuple(
        MicTiming(
            mic,
            delay,
            io.timing(
                dev, hardware, mic, stimulus, reference, directory, label, lease
            ),
        )
        for mic in range(MIC_COUNT)
    )


def _writer_counters(window: QueueWindow) -> tuple[int, ...]:
    refs = window.status["reference_outputs"]
    writer = refs["chip_ref_writer"]
    return tuple(
        int(writer[name]) for name in aec_init.REFERENCE_WRITER_COUNTER_NAMES
    )


def _commission(
    io,
    artifact_path: Path,
    hardware: Hardware,
    original_volume: float,
    rejection_dir: Path,
    lease: IsolationLease,
) -> tuple[AlignmentArtifact, dict[str, Any]]:
    stereo, reference, active = commissioning_stimulus()
    dev = None
    try:
        dev = io.reset_once(hardware)
        io.start_outputd()
        initial_queue = io.queue(hardware)
        identity = io.identity(dev, hardware, initial_queue.status)

        with tempfile.TemporaryDirectory(prefix="jasper-chip-aec-") as raw:
            directory = Path(raw)
            stimulus = directory / "commissioning.wav"
            with wave.open(str(stimulus), "wb") as wav:
                wav.setparams((2, 2, 48_000, 0, "NONE", ""))
                wav.writeframes(stereo.tobytes())

            io.apply(dev, hardware, INITIAL_SYS_DELAY, arm=False)
            if io.convergence(dev) != 0:
                raise CommissioningError("volatile reset did not clear convergence")
            level = _guarded(
                lambda: _auto_level(
                    io, hardware, stimulus, active, directory, lease
                ),
                directory, rejection_dir, lease=lease, gate="level",
            )
            log_event(logger, "chip_aec_commission.level_selected", **level)
            initial = _guarded(
                lambda: _timing_trials(
                    io, dev, hardware, INITIAL_SYS_DELAY, stimulus,
                    reference, directory, "initial", lease,
                ),
                directory, rejection_dir, lease=lease, gate="timing", phase="initial",
            )
            choice = choose_delay(initial)
            log_event(
                logger,
                "chip_aec_commission.timing_selected",
                sys_delay=choice.sys_delay,
                projected_lags=choice.projected_lags,
                worst_edge_margin=choice.worst_edge_margin,
            )

            before = io.queue(hardware)
            io.apply(dev, hardware, choice.sys_delay, arm=False)
            final = _guarded(
                lambda: _timing_trials(
                    io, dev, hardware, choice.sys_delay, stimulus,
                    reference, directory, "final", lease,
                ),
                directory, rejection_dir, lease=lease, gate="timing", phase="final",
            )
            after = io.queue(hardware)
            if len({_writer_counters(window) for window in (initial_queue, before, after)}) != 1:
                raise CommissioningError("writer errors changed during commissioning")
            before_median = median_samples(before.samples)
            queue_median = median_samples(after.samples)
            if abs(queue_median - before_median) > 2:
                raise CommissioningError("reference queue moved during final timing")
            lags, center, margin = _final_timing(final)

            io.apply(dev, hardware, choice.sys_delay, arm=True)
            chunks, seconds = _guarded(
                lambda: io.adapt_until_converged(dev, stimulus, lease),
                directory, rejection_dir, lease=lease, gate="adaptation",
            )
            # What the chip actually needed is what a later run's cap is set
            # from; it is knowable only here.
            log_event(
                logger, "chip_aec_commission.adapted", chunks=chunks, seconds=seconds,
            )
            product = _guarded(
                lambda: io.product(
                    dev, hardware, choice.sys_delay, stimulus, active, directory,
                    lease,
                ),
                directory, rejection_dir, lease=lease, gate="product",
            )
            artifact = AlignmentArtifact(
                identity, choice.sys_delay + queue_median, choice.sys_delay
            )
            # Derived at publication, never banked into the artifact (which
            # already records the DAC as identity.output_id): a verdict frozen
            # here would keep disclosing a since-approved DAC — ADR-0101.
            qualification = static_dac_qualification(identity.output_id)
            evidence: dict[str, Any] = {
                "dac_id": qualification.dac_id,
                "dac_qualification": qualification.status,
                "sys_delay": choice.sys_delay,
                "k_samples": artifact.k_samples,
                "queue_median": queue_median,
                # The window taken BEFORE the final timing, and how far the
                # median moved between the two.  The +/-2 check above is the
                # only place K's median term is cross-checked against a second
                # measurement, so its actual margin has to be in the record —
                # a spread means nothing without the count it came from, and a
                # tolerance means nothing without the delta it passed by.
                "queue_median_before": before_median,
                "queue_median_delta": queue_median - before_median,
                "queue_spread": max(after.samples) - min(after.samples),
                "queue_samples": len(after.samples),
                "chirp_seconds": round(chirp_seconds(len(stereo)), 1),
                "lags": lags,
                "center": center,
                "worst_edge_margin": margin,
                **product.evidence(),
            }
    finally:
        try:
            if dev is not None:
                io.close(dev)
        finally:
            io.restore_volume(original_volume)

    # Publication is the commit point, after device and household-volume cleanup.
    lease.check()
    atomic_write_json(
        artifact_path,
        artifact.to_dict(),
        mode=0o640,
        group_from_parent=True,
        durable=True,
    )
    return artifact, evidence


def _write_outcome(state_path: Path, *, outcome: str, detail: str) -> None:
    """Persist the last-run verdict for /aec's `commission` object.

    Best-effort by design: a status-file write failure must never mask the
    run's own verdict (the exception already propagating, or the artifact
    already published)."""
    try:
        write_outcome_record(
            state_path, CommissionOutcome.now(state=outcome, detail=detail)
        )
    except OSError as exc:
        log_event(
            logger,
            "chip_aec_commission.outcome_write_failed",
            error=str(exc),
            level=logging.WARNING,
        )


def run_commissioning(
    io=None,
    *,
    marker_path: Path = MARKER,
    artifact_path: Path = ARTIFACT_PATH,
    state_path: Path = OUTCOME_PATH,
    rejection_dir: Path = REJECTED_CAPTURE_DIR,
    effective_uid: int | None = None,
) -> AlignmentArtifact:
    if (os.geteuid() if effective_uid is None else effective_uid) != 0:
        raise CommissioningError("run jasper-aec-commission as root")
    runtime = SystemIO() if io is None else io
    _create_marker(marker_path)
    primary: BaseException | None = None
    lease: IsolationLease | None = None
    try:
        runtime.wait_reconciler_idle()
        # Zero-hardware-cost refusals (unsupported XVF, uncodified output DAC)
        # land here — before the volume move, the service stop, and the XVF
        # reset buy the same dead end.
        hardware = runtime.detect()
        # Everything audible is inside the window: the fader move, the service
        # stop, the outputd bounce, and the sweeps. The household gets one
        # clean stop here and one clean resume after the cleanup reconcile
        # below, rather than a stop, a cut, and a resume.
        lease = runtime.audio_isolation()
        lease.start()
        original_volume = runtime.prepare_volume()
        try:
            # Stop first so the arm pass hands outputd a plain start onto the
            # reference vector instead of a bounce paid twice.
            runtime.stop_services()
            # The reason routes the reconciler into its arm-only dispatch
            # (marker live): it publishes the final chip-reference vector and
            # starts outputd on it. Without that vector the resting
            # software-AEC3 env has no chip-ref writer and the
            # reference-queue preflight cannot pass. The outermost finally
            # re-runs it marker-free to restore the resting vector.
            runtime.reconcile(reason=ARM_RECONCILE_REASON)
            artifact, evidence = _commission(
                runtime, artifact_path, hardware, original_volume, rejection_dir,
                lease,
            )
        finally:
            # _commission restores on every path it enters; this covers the
            # stop/arm window before it. restore_volume no-ops when the
            # fader already matches, so the second call is free.
            runtime.restore_volume(original_volume)
        log_event(logger, "chip_aec_commission.passed", **evidence)
        _write_outcome(state_path, outcome="passed", detail="")
        print(
            "XVF chip-AEC commissioning passed: "
            f"SYS_DELAY={evidence['sys_delay']}, K={artifact.k_samples}, "
            f"lags={evidence['lags']}, suppression={evidence['beam_suppression_db']} dB"
        )
        if evidence["dac_qualification"] != STATUS_APPROVED:
            print(
                "commissioned against an unqualified DAC profile "
                f"({evidence['dac_id']}); treat the alignment as provisional"
            )
        return artifact
    except BaseException as exc:  # noqa: BLE001
        primary = exc
        log_event(
            logger, "chip_aec_commission.failed", reason=str(exc), level=logging.ERROR
        )
        _write_outcome(state_path, outcome="failed", detail=str(exc))
        raise
    finally:
        marker_path.unlink(missing_ok=True)
        try:
            runtime.reconcile()
        except BaseException as exc:  # noqa: BLE001
            if primary is not None:
                primary.add_note(f"reconcile cleanup also failed: {exc}")
            else:
                raise
        finally:
            if lease is not None:
                lease.stop()


class SystemIO:
    """Host-I/O adapter; orchestration above stays focused and testable."""

    def __init__(self) -> None:
        self.env: Mapping[str, str] = {}

    def wait_reconciler_idle(self) -> None:
        deadline = time.monotonic() + 30
        while time.monotonic() < deadline:
            result = subprocess.run(
                ["systemctl", "is-active", "jasper-aec-reconcile.service"],
                capture_output=True,
                text=True,
            )
            if result.stdout.strip() in {"inactive", "failed", "unknown"}:
                self.env = merged_env_files()
                return
            time.sleep(0.2)
        raise CommissioningError("AEC reconciler did not become idle")

    def detect(self) -> Hardware:
        profile = xvf3800.detect_runtime_profile()
        if (
            not profile.present
            or profile.capture_channels != 6
            or not profile.chip_aec_supported
            or profile.chip_beam_plan is None
        ):
            raise CommissioningError(f"unsupported XVF: {profile.reason}")
        # Registry MEMBERSHIP, not qualification: an unqualified profile
        # commissions and discloses (ADR-0101), but an unknown output edge is
        # the don't-guess refusal `output_hardware_key` already makes — made
        # here so it does not cost a service stop and an XVF reset first.
        output_id = self.env.get("JASPER_AUDIO_DAC_ID", "").strip()
        if dac_registry.by_id(output_id) is None:
            raise CommissioningError(
                f"output DAC {output_id or '<unset>'} is not in the DacProfile "
                "registry; codify its profile (jasper/audio_hardware/dac.py, "
                "docs/PROPOSAL-dac-profile-registry.md) before commissioning"
            )
        return Hardware(profile.variant_id, profile.alsa_card_name, profile.chip_beam_plan)

    def set_volume(self, db: float) -> None:
        declare_main_volume_db(db)
        if not fader_matches(read_main_volume_db(), db):
            raise CommissioningError("commissioning volume did not verify")
        # No capture may start inside CamillaDSP's own volume ramp.
        time.sleep(MAIN_VOLUME_RAMP_SETTLE_S)

    def prepare_volume(self) -> float:
        original = read_main_volume_db()
        try:
            self.set_volume(MEASUREMENT_VOLUME_DB)
        except BaseException:  # noqa: BLE001 - restore household volume on interrupt
            declare_main_volume_db(original)
            raise
        return original

    def restore_volume(self, original: float) -> None:
        if not fader_matches(read_main_volume_db(), original):
            declare_main_volume_db(original)

    def stop_services(self) -> None:
        _run(("systemctl", "stop", *STOP_UNITS))

    def audio_isolation(self) -> IsolationLease:
        return IsolationLease(COMMISSION_GATE_OWNER)

    def reset_once(self, hardware: Hardware):
        from jasper.xvf import xvf_host

        old = xvf_host.find()
        if old is None:
            raise CommissioningError("XVF control interface is unavailable")
        transfer_error = None
        try:
            old_serial = aec_init.xvf_factory_serial(old)
            try:
                old.reboot_once()
            except Exception as exc:  # noqa: BLE001  # disappearance can race USB
                transfer_error = exc
        finally:
            old.close()
        card_path = Path("/proc/asound") / hardware.card
        deadline = time.monotonic() + 10
        while card_path.exists() and time.monotonic() < deadline:
            time.sleep(0.1)
        if card_path.exists():
            raise CommissioningError(f"XVF did not disappear after reset: {transfer_error}")
        deadline = time.monotonic() + 30
        dev = None
        while time.monotonic() < deadline:
            if card_path.exists():
                dev = xvf_host.find()
                if dev is not None:
                    break
            time.sleep(0.1)
        if dev is None:
            raise CommissioningError("XVF did not re-enumerate after reset")
        try:
            if aec_init.xvf_factory_serial(dev) != old_serial:
                raise CommissioningError("XVF physical identity changed across reset")
            current = self.detect()
            if (current.variant, current.card, current.plan.plan_id) != (
                hardware.variant, hardware.card, hardware.plan.plan_id
            ):
                raise CommissioningError("XVF identity changed across reset")
            aec_init.write_required(dev, "SHF_BYPASS", [1])
            aec_init.set_uac_unity(hardware.card)
        except BaseException:  # noqa: BLE001 - never leak a rejected USB handle
            dev.close()
            raise
        return dev

    def start_outputd(self) -> None:
        _run(("systemctl", "start", "jasper-outputd.service"))

    def queue(self, hardware: Hardware) -> QueueWindow:
        status, samples = aec_init.collect_reference_queue(
            aec_init.native_reference_pcm(hardware.card)
        )
        return QueueWindow(status, samples)

    def identity(self, dev, hardware: Hardware, status: Mapping[str, Any]):
        env = dict(self.env)
        env["JASPER_XVF_VARIANT"] = hardware.variant
        return aec_init.build_identity(dev, hardware.plan, status, env=env)

    def apply(self, dev, hardware: Hardware, delay: int, *, arm: bool) -> None:
        aec_init.apply_profile(dev, hardware.plan, delay, card=hardware.card, arm=arm)

    def convergence(self, dev) -> int:
        value = dev.read("AEC_AECCONVERGED")
        if not isinstance(value, Sequence) or len(value) != 1:
            raise CommissioningError("AEC convergence readback is invalid")
        return int(value[0])

    def _capture(
        self, hardware: Hardware, stimulus: Path, output: Path,
        lease: IsolationLease,
    ) -> np.ndarray:
        # EVERY capture this CLI plays comes through here — the warm-up probe,
        # each timing trial, both product captures — so this is the one place
        # that makes "no capture plays over the household" true per capture
        # rather than per phase.
        lease.check()
        recorder = subprocess.Popen(
            [
                "arecord", "-q", "-D", f"hw:CARD={hardware.card},DEV=0",
                "-d", str(CAPTURE_SECONDS), "-f", "S16_LE", "-r", "16000",
                "-c", "6", str(output),
            ]
        )
        try:
            time.sleep(CAPTURE_LEAD_SECONDS)
            _play_correction(stimulus, timeout=5)
            if recorder.wait(timeout=5):
                raise CommissioningError("XVF capture failed")
        finally:
            if recorder.poll() is None:
                recorder.terminate()
                recorder.wait(timeout=2)
        return read_capture(output)

    def timing(
        self, dev, hardware: Hardware, mic: int, stimulus: Path,
        reference: np.ndarray, directory: Path, label: str,
        lease: IsolationLease,
    ) -> tuple[int, ...]:
        aec_init.write_required(dev, "AUDIO_MGR_OP_L", [3, mic])
        aec_init.write_required(dev, "AUDIO_MGR_OP_R", [12, 0])
        trials = []
        for trial in range(TIMING_TRIALS):
            capture = self._capture(
                hardware, stimulus, directory / f"{label}-m{mic}-{trial}.wav",
                lease,
            )
            result = analyze_timing(capture, reference)
            trials.append(result.lag)
            log_event(
                logger, "chip_aec_commission.timing_trial",
                phase=label, mic=mic, trial=trial + 1, **result.evidence(),
            )
        return tuple(trials)

    def warmup(
        self, hardware: Hardware, stimulus: Path, active: np.ndarray,
        directory: Path, lease: IsolationLease,
    ) -> LevelProbe:
        return analyze_level(
            self._capture(
                hardware, stimulus, directory / WARMUP_CAPTURE_NAME, lease
            ),
            active,
        )

    def adapt_until_converged(
        self, dev, stimulus: Path, lease: IsolationLease
    ) -> tuple[int, float]:
        """Play adaptation chunks until the chip converges.

        Returns the chunks played and the seconds they took — measured, because
        that number is what a later run's cap is set from.
        """

        started = time.monotonic()
        for chunks in range(1, ADAPTATION_CHUNKS + 1):
            lease.check()
            self.adapt(stimulus)
            if self.convergence(dev) == 1:
                return chunks, round(time.monotonic() - started, 1)
        raise Rejected(
            "adaptation",
            {
                "chunks_played": ADAPTATION_CHUNKS,
                "adaptation_seconds": round(time.monotonic() - started, 1),
                "converged": 0,
            },
        )

    def adapt(self, stimulus: Path) -> None:
        _play_correction(stimulus, timeout=5)

    def product(
        self, dev, hardware: Hardware, delay: int, stimulus: Path,
        active: np.ndarray, directory: Path, lease: IsolationLease,
    ) -> ProductResult:
        on = self._capture(hardware, stimulus, directory / "aec-on.wav", lease)
        aec_init.write_required(dev, "SHF_BYPASS", [1])
        try:
            off = self._capture(
                hardware, stimulus, directory / "aec-off.wav", lease
            )
        finally:
            self.apply(dev, hardware, delay, arm=True)
        log_event(
            logger,
            "chip_aec_commission.product_capture",
            beam_on_rms_dbfs=round(dbfs_rms(on[:, :2]), 2),
            beam_off_rms_dbfs=round(dbfs_rms(off[:, :2]), 2),
            raw_on_rms_dbfs=round(dbfs_rms(on[:, 2:]), 2),
            raw_off_rms_dbfs=round(dbfs_rms(off[:, 2:]), 2),
        )
        return analyze_product(on, off, active)

    def close(self, dev) -> None:
        dev.close()

    def reconcile(self, *, reason: str = _CLEANUP_RECONCILE_REASON) -> None:
        _run(("/usr/local/sbin/jasper-aec-reconcile", "--reason", reason))


def _signal(signum: int, _frame: FrameType | None) -> None:
    raise CommissioningError(f"received signal {signum}")


def _emit_class_entry(path: Path) -> int:
    """Print this artifact as a shipped hardware-class row, and change nothing.

    The harvest step behind `jasper.chip_aec.shipped`: one file read,
    source to stdout, no chip, no network, no writes — so it runs off a copied
    artifact on a laptop as readily as on the box that commissioned it.
    """

    artifact = load_artifact(path)
    print(render_entry(artifact.identity, artifact.k_samples, artifact.sys_delay))
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="jasper-aec-commission")
    parser.add_argument(
        "--emit-class-entry",
        nargs="?",
        const=str(ARTIFACT_PATH),
        metavar="ARTIFACT",
        help=(
            "read a commissioned alignment artifact (default: this box's) and "
            "print it as a jasper.chip_aec.shipped registry entry, "
            "then exit without commissioning anything"
        ),
    )
    args = parser.parse_args(argv)
    logging.basicConfig(
        level=logging.INFO, format="%(asctime)s aec-commission %(levelname)s %(message)s"
    )
    # `prepare_volume`/`restore_volume` write the main fader through
    # `camilla.declare_main_volume_db`, which declares through the process
    # owner. Registered AFTER the `--emit-class-entry` early exit: that
    # path prints a registry row and touches no hardware, so it should not
    # build a Camilla controller. See tests/test_canonical_target_registration.py.
    from jasper.volume_coordinator import install_env_canonical_target_provider

    install_env_canonical_target_provider()
    handlers = {
        signum: signal.signal(signum, _signal) for signum in (signal.SIGTERM, signal.SIGHUP)
    }
    try:
        # Presence, not truthiness: an unset shell variable makes the flag
        # arrive as "", and falling through on that would start a full
        # commissioning run (services stopped, audible sweeps, chip writes) for
        # someone who asked to print a registry row.
        if args.emit_class_entry is not None:
            return _emit_class_entry(Path(args.emit_class_entry))
        run_commissioning()
        return 0
    except (OSError, ValueError, RuntimeError, subprocess.SubprocessError, KeyboardInterrupt) as exc:
        print(f"jasper-aec-commission: {exc}", file=sys.stderr)
        return 1
    finally:
        for signum, handler in handlers.items():
            signal.signal(signum, handler)


if __name__ == "__main__":
    sys.exit(main())
