# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Audio hardware profile registries."""
from __future__ import annotations

from .dac import (
    APPLE_HEADPHONE_CONTROL,
    APPLE_USB_C_DONGLE,
    APPLE_USB_C_DONGLE_ID,
    DAC8X_OUTPUTD_STABILITY_PROFILE,
    DUAL_APPLE_USB_C_DAC_4CH,
    DUAL_APPLE_USB_C_DAC_4CH_ID,
    ClockDomainContract,
    DacKind,
    DacProfile,
    HIFIBERRY_DAC8X,
    HIFIBERRY_DAC8X_ID,
    HIFIBERRY_DAC8X_STUDIO,
    HIFIBERRY_DAC8X_STUDIO_ID,
    MixerControl,
    REGISTRY,
    active_outputd_lane_channels_for,
    all_profiles,
    by_id,
    clock_domain_contract_for,
    clock_domain_label_for,
    is_known_profile_id,
    known_profile_ids,
    label_for,
    mixer_control_groups_for,
    profile_for_card_label,
    physical_output_count_for,
    supports_physical_output_count,
)

__all__ = [
    "APPLE_HEADPHONE_CONTROL",
    "APPLE_USB_C_DONGLE",
    "APPLE_USB_C_DONGLE_ID",
    "DAC8X_OUTPUTD_STABILITY_PROFILE",
    "DUAL_APPLE_USB_C_DAC_4CH",
    "DUAL_APPLE_USB_C_DAC_4CH_ID",
    "ClockDomainContract",
    "DacKind",
    "DacProfile",
    "HIFIBERRY_DAC8X",
    "HIFIBERRY_DAC8X_ID",
    "HIFIBERRY_DAC8X_STUDIO",
    "HIFIBERRY_DAC8X_STUDIO_ID",
    "MixerControl",
    "REGISTRY",
    "active_outputd_lane_channels_for",
    "all_profiles",
    "by_id",
    "clock_domain_contract_for",
    "clock_domain_label_for",
    "is_known_profile_id",
    "known_profile_ids",
    "label_for",
    "mixer_control_groups_for",
    "profile_for_card_label",
    "physical_output_count_for",
    "supports_physical_output_count",
]
