#!/usr/bin/env python3
"""Run the Phase 0 custom wake-word training workflow.

This is an off-Pi operator runner. It wires together the existing JTS wake
training tools:

1. export positive wake-corpus recordings into a bundle,
2. build positive openWakeWord feature banks,
3. export/build real negative feature banks,
4. prepare the real-positive training workdir,
5. prepare, and optionally run, the LiveKit train/export/eval smoke harness.

The runner does not generate synthetic positive audio, launch cloud jobs,
register a model, deploy a model, or alter Pi runtime state.
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable


SCHEMA_VERSION = 1
DEFAULT_POSITIVE_CORPUS_DIR = Path("data/enrollment_positives")
DEFAULT_OUTPUT_ROOT = Path("logs/wake-training-phase0")


@dataclass(frozen=True)
class CommandResult:
    command: list[str]
    returncode: int
    duration_sec: float
    stdout: str
    stderr: str


CommandRunner = Callable[[list[str], Path], CommandResult]


class Phase0Error(RuntimeError):
    pass


def _utc_now() -> datetime:
    return datetime.now(timezone.utc)


def _timestamp(now: datetime | None = None) -> str:
    return (now or _utc_now()).strftime("%Y%m%dT%H%M%SZ")


def _repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def _default_output_dir(now: datetime | None = None) -> Path:
    return DEFAULT_OUTPUT_ROOT / _timestamp(now)


def _script(name: str) -> Path:
    return _repo_root() / "scripts" / name


def _run_command(command: list[str], cwd: Path) -> CommandResult:
    started = time.monotonic()
    completed = subprocess.run(  # noqa: S603 - command is built from fixed script paths.
        command,
        cwd=str(cwd),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return CommandResult(
        command=command,
        returncode=completed.returncode,
        duration_sec=round(time.monotonic() - started, 3),
        stdout=completed.stdout,
        stderr=completed.stderr,
    )


def _safe_to_remove_output(path: Path) -> bool:
    resolved = path.expanduser().resolve()
    blocked = {
        Path("/").resolve(),
        Path.home().resolve(),
        Path.cwd().resolve(),
        _repo_root().resolve(),
    }
    if resolved in blocked:
        return False
    root = (Path.cwd() / DEFAULT_OUTPUT_ROOT).resolve()
    return resolved == root or root in resolved.parents or _looks_like_phase0_output(resolved)


def _looks_like_phase0_output(path: Path) -> bool:
    marker = path / "phase0_run.json"
    if not marker.is_file():
        return False
    try:
        data = _read_json(marker)
    except (OSError, json.JSONDecodeError, ValueError):
        return False
    return data.get("schema_version") == SCHEMA_VERSION and data.get("tool") == "run-wake-training-phase0"


def _non_empty(path: Path) -> bool:
    return path.exists() and any(path.iterdir())


def _read_json(path: Path) -> dict[str, Any]:
    with open(path) as f:
        data = json.load(f)
    if not isinstance(data, dict):
        raise ValueError(f"{path} does not contain a JSON object")
    return data


def _sha256(path: Path) -> str:
    import hashlib

    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def _tail(value: str, limit: int = 4000) -> str:
    if len(value) <= limit:
        return value
    return value[-limit:]


def _write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")


def _write_readme(path: Path, *, run_livekit: bool, allow_placeholder_negatives: bool) -> None:
    lines = [
        "# Wake Training Phase 0 Run",
        "",
        "This directory was generated by `scripts/run-wake-training-phase0.sh`.",
        "",
        "Use this as an evidence bundle for a tiny off-Pi custom wake-word",
        "train/eval loop. It is not a production model registry and it does",
        "not activate anything on a speaker.",
        "",
        "Key files:",
        "",
        "- `phase0_run.json` - top-level run manifest and command outcomes.",
        "- `command_log.jsonl` - bounded stdout/stderr tails for each step.",
        "- `positive-bundle/` - exported wake-positive corpus bundle, unless",
        "  an existing `--positive-bundle-dir` was supplied.",
        "- `positive-features/` - real-positive openWakeWord feature bank.",
        "- `negative-bundle/` - exported negative corpus bundle, unless an",
        "  existing `--negative-bundle-dir` was supplied.",
        "- `negative-features/` - real negative/hard-negative feature bank.",
        "- `training-workdir/` - real-positive LiveKit/openWakeWord workdir.",
        "- `livekit-phase0/` - LiveKit-compatible train/export/eval workdir.",
        "",
        "Interpretation:",
        "",
        "- Real model-quality evidence requires real negative features.",
        "- The exported ONNX, if produced, is still a candidate artifact; do",
        "  not deploy it until it beats the incumbent on held-out JTS audio.",
    ]
    if allow_placeholder_negatives:
        lines.extend([
            "",
            "Warning: this run allowed placeholder negatives. Treat it as a",
            "mechanics-only smoke test, not quality evidence.",
        ])
    if not run_livekit:
        lines.extend([
            "",
            "LiveKit was not run. To train/export/eval on this host, rerun with",
            "`--run-livekit` after installing livekit-wakeword training deps.",
        ])
    path.write_text("\n".join(lines) + "\n")


def _append_command_log(path: Path, *, step: str, result: CommandResult) -> None:
    row = {
        "schema_version": SCHEMA_VERSION,
        "step": step,
        "command": result.command,
        "returncode": result.returncode,
        "duration_sec": result.duration_sec,
        "stdout_tail": _tail(result.stdout),
        "stderr_tail": _tail(result.stderr),
    }
    with open(path, "a") as f:
        f.write(json.dumps(row, sort_keys=True) + "\n")


def _command_summary(step: str, result: CommandResult, *, artifacts: dict[str, str]) -> dict[str, Any]:
    return {
        "step": step,
        "command": result.command,
        "returncode": result.returncode,
        "duration_sec": result.duration_sec,
        "stdout_tail": _tail(result.stdout),
        "stderr_tail": _tail(result.stderr),
        "artifacts": artifacts,
    }


def _run_step(
    *,
    step: str,
    command: list[str],
    cwd: Path,
    command_log: Path,
    runner: CommandRunner,
    artifacts: dict[str, str],
    steps: list[dict[str, Any]],
) -> dict[str, Any]:
    result = runner(command, cwd)
    _append_command_log(command_log, step=step, result=result)
    summary = _command_summary(step, result, artifacts=artifacts)
    steps.append(summary)
    if result.returncode != 0:
        raise Phase0Error(f"{step} failed with exit code {result.returncode}")
    return summary


def _extend_repeatable(command: list[str], flag: str, values: list[str] | None) -> None:
    for value in values or []:
        command.extend([flag, value])


def _maybe_extend(command: list[str], flag: str, value: object | None) -> None:
    if value is not None:
        command.extend([flag, str(value)])


def _feature_file(summary_path: Path, split: str) -> Path:
    summary = _read_json(summary_path)
    artifacts = summary.get("artifacts")
    if not isinstance(artifacts, dict):
        raise ValueError(f"{summary_path} missing artifacts object")
    features = artifacts.get("features")
    if not isinstance(features, dict):
        raise ValueError(f"{summary_path} missing artifacts.features object")
    file_name = features.get(split)
    if not isinstance(file_name, str) or not file_name:
        raise ValueError(f"{summary_path} missing feature file for split {split!r}")
    return summary_path.parent / file_name


def _run_phase0(args: argparse.Namespace, *, runner: CommandRunner = _run_command) -> dict[str, Any]:
    repo = _repo_root()
    output_dir = (Path(args.output_dir) if args.output_dir else _default_output_dir()).expanduser()
    output_dir = output_dir.resolve()
    if _non_empty(output_dir):
        if not args.force:
            raise Phase0Error(f"output directory is not empty: {output_dir} (pass --force)")
        if not _safe_to_remove_output(output_dir):
            raise Phase0Error(f"refusing to remove unsafe output directory: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    command_log = output_dir / "command_log.jsonl"
    _write_readme(
        output_dir / "README.md",
        run_livekit=bool(args.run_livekit),
        allow_placeholder_negatives=bool(args.allow_placeholder_negatives),
    )

    steps: list[dict[str, Any]] = []
    status = "pass"
    error: str | None = None

    positive_bundle = (
        Path(args.positive_bundle_dir).expanduser().resolve()
        if args.positive_bundle_dir
        else output_dir / "positive-bundle"
    )
    positive_features = output_dir / "positive-features"
    negative_bundle = (
        Path(args.negative_bundle_dir).expanduser().resolve()
        if args.negative_bundle_dir
        else (output_dir / "negative-bundle" if args.negative_corpus_dir else None)
    )
    negative_features = output_dir / "negative-features"
    training_workdir = output_dir / "training-workdir"
    livekit_dir = output_dir / "livekit-phase0"

    try:
        if not args.negative_corpus_dir and not args.negative_bundle_dir and not args.allow_placeholder_negatives:
            raise Phase0Error(
                "Phase 0 quality runs require --negative-corpus-dir or --negative-bundle-dir. "
                "Pass --allow-placeholder-negatives only for a mechanics smoke test."
            )
        if args.negative_corpus_dir and args.negative_bundle_dir:
            raise Phase0Error("--negative-corpus-dir and --negative-bundle-dir are mutually exclusive")
        if args.positive_bundle_dir and (args.latest is not None or args.session):
            raise Phase0Error("--latest/--session apply only when exporting --positive-corpus-dir")
        if args.negative_bundle_dir and (args.negative_latest is not None or args.negative_session):
            raise Phase0Error(
                "--negative-latest/--negative-session apply only when exporting --negative-corpus-dir"
            )

        if args.positive_bundle_dir:
            if not (positive_bundle / "bundle.json").is_file():
                raise Phase0Error(f"{positive_bundle}/bundle.json not found")
        else:
            command = [
                "bash",
                str(_script("export-wake-corpus-bundle.sh")),
                str(Path(args.positive_corpus_dir)),
                str(positive_bundle),
                "--eval-fraction",
                str(args.eval_fraction),
                "--seed",
                str(args.seed),
            ]
            _extend_repeatable(command, "--session", args.session)
            _maybe_extend(command, "--latest", args.latest)
            if args.include_deleted:
                command.append("--include-deleted")
            _run_step(
                step="export_positive_bundle",
                command=command,
                cwd=repo,
                command_log=command_log,
                runner=runner,
                artifacts={"bundle": str(positive_bundle / "bundle.json")},
                steps=steps,
            )

        command = [
            "bash",
            str(_script("build-wake-feature-bank.sh")),
            str(positive_bundle),
            str(positive_features),
            "--batch-size",
            str(args.batch_size),
            "--ncpu",
            str(args.ncpu),
            "--device",
            args.device,
        ]
        _extend_repeatable(command, "--leg", args.positive_leg)
        _extend_repeatable(command, "--profile", args.positive_profile)
        _maybe_extend(command, "--melspec-model", args.melspec_model)
        _maybe_extend(command, "--embedding-model", args.embedding_model)
        _run_step(
            step="build_positive_features",
            command=command,
            cwd=repo,
            command_log=command_log,
            runner=runner,
            artifacts={"summary": str(positive_features / "feature_bank.json")},
            steps=steps,
        )

        if args.allow_placeholder_negatives and negative_bundle is None:
            negative_train_path = None
            negative_test_path = None
        else:
            assert negative_bundle is not None
            if args.negative_bundle_dir:
                if not (negative_bundle / "bundle.json").is_file():
                    raise Phase0Error(f"{negative_bundle}/bundle.json not found")
            else:
                command = [
                    "bash",
                    str(_script("export-wake-corpus-bundle.sh")),
                    str(Path(args.negative_corpus_dir)),
                    str(negative_bundle),
                    "--eval-fraction",
                    str(args.negative_eval_fraction),
                    "--seed",
                    str(args.negative_seed),
                ]
                _extend_repeatable(command, "--session", args.negative_session)
                _maybe_extend(command, "--latest", args.negative_latest)
                if args.include_deleted:
                    command.append("--include-deleted")
                _run_step(
                    step="export_negative_bundle",
                    command=command,
                    cwd=repo,
                    command_log=command_log,
                    runner=runner,
                    artifacts={"bundle": str(negative_bundle / "bundle.json")},
                    steps=steps,
                )

            command = [
                "bash",
                str(_script("build-wake-negative-feature-bank.sh")),
                str(negative_bundle),
                str(negative_features),
                "--batch-size",
                str(args.batch_size),
                "--ncpu",
                str(args.ncpu),
                "--device",
                args.device,
            ]
            _extend_repeatable(command, "--leg", args.negative_leg)
            _extend_repeatable(command, "--profile", args.negative_profile)
            _extend_repeatable(command, "--condition", args.negative_condition)
            _extend_repeatable(command, "--distance", args.negative_distance)
            _extend_repeatable(command, "--label-kind", args.negative_label_kind)
            _maybe_extend(command, "--allow-unlabeled-as", args.allow_unlabeled_negative_as)
            _maybe_extend(command, "--melspec-model", args.melspec_model)
            _maybe_extend(command, "--embedding-model", args.embedding_model)
            _run_step(
                step="build_negative_features",
                command=command,
                cwd=repo,
                command_log=command_log,
                runner=runner,
                artifacts={"summary": str(negative_features / "negative_feature_bank.json")},
                steps=steps,
            )
            negative_train_path = _feature_file(
                negative_features / "negative_feature_bank.json",
                "train",
            )
            negative_test_path = _feature_file(
                negative_features / "negative_feature_bank.json",
                "eval",
            )

        command = [
            "bash",
            str(_script("prepare-wake-training-workdir.sh")),
            str(positive_features),
            str(training_workdir),
            "--target-phrase",
            args.target_phrase,
            "--positive-weight",
            str(args.positive_weight),
        ]
        _maybe_extend(command, "--model-name", args.model_name)
        _run_step(
            step="prepare_training_workdir",
            command=command,
            cwd=repo,
            command_log=command_log,
            runner=runner,
            artifacts={"summary": str(training_workdir / "training_workdir.json")},
            steps=steps,
        )

        command = [
            "bash",
            str(_script("prepare-wake-livekit-smoke.sh")),
            str(training_workdir),
            str(livekit_dir),
            "--target-phrase",
            args.target_phrase,
            "--steps",
            str(args.steps),
            "--model-type",
            args.model_type,
            "--model-size",
            args.model_size,
            "--target-fp-per-hour",
            str(args.target_fp_per_hour),
        ]
        _maybe_extend(command, "--model-name", args.model_name)
        if negative_train_path is not None:
            command.extend(["--negative-train-features", str(negative_train_path)])
        if negative_test_path is not None:
            command.extend(["--negative-test-features", str(negative_test_path)])
        if args.run_livekit:
            command.append("--run-livekit")
        _run_step(
            step="prepare_livekit_phase0",
            command=command,
            cwd=repo,
            command_log=command_log,
            runner=runner,
            artifacts={"summary": str(livekit_dir / "livekit_smoke.json")},
            steps=steps,
        )
    except Exception as e:  # noqa: BLE001
        status = "fail"
        error = str(e)

    artifacts: dict[str, Any] = {
        "readme": "README.md",
        "command_log": "command_log.jsonl",
        "phase0_run": "phase0_run.json",
        "positive_bundle": str(positive_bundle),
        "positive_feature_bank": str(positive_features / "feature_bank.json"),
        "training_workdir": str(training_workdir / "training_workdir.json"),
        "livekit": str(livekit_dir / "livekit_smoke.json"),
    }
    if negative_bundle is not None:
        artifacts["negative_bundle"] = str(negative_bundle)
        artifacts["negative_feature_bank"] = str(negative_features / "negative_feature_bank.json")
    artifact_hashes: dict[str, str] = {}
    for key, value in artifacts.items():
        candidate = Path(value)
        if candidate.is_file():
            artifact_hashes[key] = _sha256(candidate)

    manifest = {
        "schema_version": SCHEMA_VERSION,
        "created_at": _utc_now().isoformat(timespec="seconds"),
        "tool": "run-wake-training-phase0",
        "status": status,
        "error": error,
        "output_dir": str(output_dir),
        "inputs": {
            "positive_corpus_dir": str(Path(args.positive_corpus_dir)),
            "positive_bundle_dir": str(Path(args.positive_bundle_dir)) if args.positive_bundle_dir else None,
            "negative_corpus_dir": str(Path(args.negative_corpus_dir)) if args.negative_corpus_dir else None,
            "negative_bundle_dir": str(Path(args.negative_bundle_dir)) if args.negative_bundle_dir else None,
            "allow_placeholder_negatives": bool(args.allow_placeholder_negatives),
        },
        "configuration": {
            "target_phrase": args.target_phrase,
            "model_name": args.model_name,
            "positive_weight": args.positive_weight,
            "steps": args.steps,
            "model_type": args.model_type,
            "model_size": args.model_size,
            "target_fp_per_hour": args.target_fp_per_hour,
            "run_livekit": bool(args.run_livekit),
            "positive_leg": args.positive_leg,
            "positive_profile": args.positive_profile,
            "negative_label_kind": args.negative_label_kind,
        },
        "steps": steps,
        "artifacts": artifacts,
        "artifact_sha256": artifact_hashes,
        "quality_evidence": {
            "real_negative_features": negative_bundle is not None,
            "placeholder_negatives": negative_bundle is None,
            "livekit_run_requested": bool(args.run_livekit),
        },
        "limitations": [
            "does not generate synthetic positive audio",
            "does not launch cloud jobs",
            "does not register, deploy, or activate a model",
            "does not alter Pi runtime state",
            "positive input is assumed to contain wake-positive utterances",
        ],
        "next_steps": [
            "inspect livekit-phase0/livekit_smoke.json for train/export/eval command results",
            "compare any exported ONNX against the incumbent on held-out JTS audio",
            "only then decide whether to build cloud orchestration or model registry plumbing",
        ],
    }
    _write_json(output_dir / "phase0_run.json", manifest)
    if status != "pass":
        raise Phase0Error(error or "phase0 run failed")
    return manifest


def _build_parser() -> argparse.ArgumentParser:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "output_dir",
        nargs="?",
        help="Output run directory (default: logs/wake-training-phase0/<UTC timestamp>)",
    )
    ap.add_argument(
        "--positive-corpus-dir",
        default=str(DEFAULT_POSITIVE_CORPUS_DIR),
        help=f"Wake-positive corpus directory to export (default: {DEFAULT_POSITIVE_CORPUS_DIR})",
    )
    ap.add_argument(
        "--positive-bundle-dir",
        help="Use an existing positive bundle instead of exporting --positive-corpus-dir",
    )
    ap.add_argument("--negative-corpus-dir", help="Negative/hard-negative corpus directory to export")
    ap.add_argument("--negative-bundle-dir", help="Existing negative/hard-negative bundle")
    ap.add_argument(
        "--allow-placeholder-negatives",
        action="store_true",
        help="Allow mechanics-only LiveKit smoke with placeholder negatives",
    )
    ap.add_argument("--session", action="append", help="Positive corpus session id to export")
    ap.add_argument("--latest", type=int, help="Export latest N positive sessions")
    ap.add_argument("--negative-session", action="append", help="Negative corpus session id to export")
    ap.add_argument("--negative-latest", type=int, help="Export latest N negative sessions")
    ap.add_argument("--eval-fraction", type=float, default=0.2, help="Positive eval split fraction")
    ap.add_argument("--negative-eval-fraction", type=float, default=0.2, help="Negative eval split fraction")
    ap.add_argument("--seed", type=int, default=42, help="Positive split seed")
    ap.add_argument("--negative-seed", type=int, default=43, help="Negative split seed")
    ap.add_argument("--include-deleted", action="store_true", help="Pass through to bundle export")
    ap.add_argument("--positive-leg", action="append", help="Positive leg filter")
    ap.add_argument("--positive-profile", action="append", help="Positive profile filter")
    ap.add_argument("--negative-leg", action="append", help="Negative leg filter")
    ap.add_argument("--negative-profile", action="append", help="Negative profile filter")
    ap.add_argument("--negative-condition", action="append", help="Negative condition filter")
    ap.add_argument("--negative-distance", action="append", help="Negative distance filter")
    ap.add_argument("--negative-label-kind", action="append", help="Negative label kind filter")
    ap.add_argument(
        "--allow-unlabeled-negative-as",
        help="Treat unlabeled negative rows as this non-wake label kind",
    )
    ap.add_argument("--target-phrase", default="hey jarvis", help="Wake phrase")
    ap.add_argument("--model-name", help="Model name")
    ap.add_argument("--positive-weight", type=int, default=3, help="Real-positive train repeat weight")
    ap.add_argument("--steps", type=int, default=20, help="LiveKit smoke training steps")
    ap.add_argument(
        "--model-type",
        choices=["dnn", "rnn", "conv_attention"],
        default="conv_attention",
        help="LiveKit model type",
    )
    ap.add_argument(
        "--model-size",
        choices=["tiny", "small", "medium", "large"],
        default="tiny",
        help="LiveKit model size",
    )
    ap.add_argument("--target-fp-per-hour", type=float, default=0.5, help="LiveKit eval target FPPH")
    ap.add_argument("--batch-size", type=int, default=32, help="Feature extraction batch size")
    ap.add_argument("--ncpu", type=int, default=1, help="openWakeWord CPU thread count")
    ap.add_argument("--device", choices=["cpu", "gpu"], default="cpu", help="openWakeWord device")
    ap.add_argument("--melspec-model", help="Path to melspectrogram.onnx")
    ap.add_argument("--embedding-model", help="Path to embedding_model.onnx")
    ap.add_argument("--run-livekit", action="store_true", help="Run livekit-wakeword train/export/eval")
    ap.add_argument("--force", action="store_true", help="Replace a previous generated output dir")
    return ap


def main(argv: list[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(argv)
    try:
        summary = _run_phase0(args)
    except Phase0Error as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    print("Wake training Phase 0 run")
    print("=" * 60)
    print(f"  status    : {summary['status']}")
    print(f"  output    : {summary['output_dir']}")
    print(f"  livekit   : {summary['artifacts']['livekit']}")
    print(f"  run file  : {summary['artifacts']['phase0_run']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
