# SPDX-FileCopyrightText: 2026 Jasper Curry
#
# SPDX-License-Identifier: Apache-2.0

"""Active-speaker crossover commissioning substrate.

Most of this package does not emit audio or grant playback authority — the
exception is `web_commissioning`, whose safety-gated driver/summed test and
capture-sweep flows launch `aplay` / `play_sweep` to produce real hardware
audio.

Package-level names resolve lazily (PEP 562): importing a submodule such as
`volume_latch` must not drag the measurement stack (yaml, numpy/scipy via
`jasper.audio_measurement`) into a resident daemon.
"""

from importlib import import_module
from typing import Any

_LAZY_ATTRS: dict[str, str] = {
    "ACTIVE_BASELINE_KIND": "profile",
    "ACTIVE_PLAYBACK_DEVICE_ENV": "staging",
    "ACTIVE_PRESET_KIND": "profile",
    "ACTIVE_PROGRAM_BAKE_SOURCE": "camilla_yaml",
    "ActiveChannelMap": "profile",
    "ActiveSpeakerConfigError": "profile",
    "ActiveSpeakerDesignDraftError": "design_draft",
    "ActiveSpeakerPreset": "profile",
    "AplayTonePlaybackBackend": "playback",
    "BASELINE_HEADROOM_DB": "camilla_yaml",
    "BASELINE_LIMITER_CLIP_LIMIT_DB": "camilla_yaml",
    "BASELINE_PROFILE_KIND": "baseline_profile",
    "BRINGUP_PREFLIGHT_KIND": "bringup",
    "BaselineVerification": "profile",
    "CALIBRATION_LEVEL_KIND": "calibration_level",
    "COMMISSIONING_CONFIG_KIND": "staging",
    "COMMISSIONING_HEADROOM_DB": "camilla_yaml",
    "COMMISSION_LOAD_PREFLIGHT_KIND": "startup_load",
    "COMMISSION_LOAD_STATE_ENV": "state_paths",
    "COMMISSION_LOAD_STATE_KIND": "startup_load",
    "COMMISSION_RAMP_MAX_LEVEL_DBFS": "commission_ramp",
    "CROSSOVER_PREVIEW_KIND": "crossover_preview",
    "CROSSOVER_PREVIEW_PATH_ENV": "crossover_preview",
    "CrossoverAlignmentProposal": "crossover_alignment",
    "CrossoverRegion": "profile",
    "DEFAULT_PATH_SAFETY_EVIDENCE_PATH": "path_safety",
    "DEFAULT_PRESET_RESOURCE": "tone_plan",
    "DEFAULT_TEST_LEVEL_DBFS": "calibration_level",
    "DESIGN_DRAFT_KIND": "design_draft",
    "DESIGN_DRAFT_PATH_ENV": "design_draft",
    "DRIVER_ACOUSTIC_KIND": "driver_acoustics",
    "DRIVER_DOMAIN_PROGRAM_CHANNELS": "camilla_yaml",
    "DRIVER_PROTECTION_KIND": "driver_protection",
    "DRIVER_PROTECTION_POLICY_VERSION": "driver_protection",
    "DRIVER_RESEARCH_KIND": "design_draft",
    "DRIVER_RESEARCH_REQUEST_KIND": "driver_safety",
    "DRIVER_RESEARCH_REQUEST_SCHEMA_VERSION": "driver_safety",
    "DRIVER_RESEARCH_RESULT_SCHEMA_VERSION": "driver_safety",
    "DRIVER_SAFETY_PROFILE_KIND": "driver_safety",
    "DRIVER_SAFETY_PROFILE_SCHEMA_VERSION": "driver_safety",
    "DRIVER_TEST_SIGNAL_PLAN_KIND": "test_signal_plan",
    "DRIVER_VERDICTS": "driver_acoustics",
    "DRIVER_VERDICT_TO_OUTCOME": "commissioning_capture",
    "DriverAcousticResult": "driver_acoustics",
    "DriverAcousticsError": "driver_acoustics",
    "DriverSafetyProfileError": "driver_safety",
    "DriverSafetyProfileEvaluation": "driver_safety",
    "DriverSpec": "profile",
    "DriverSweep": "driver_acoustics",
    "ENVIRONMENT_REPORT_KIND": "environment",
    "GRAPH_ALL_MUTED_ACTIVE_STARTUP": "runtime_contract",
    "GRAPH_DRIVER_DOMAIN_BASELINE": "runtime_contract",
    "GRAPH_FLAT_FULL_RANGE": "runtime_contract",
    "GRAPH_GUARDED_COMMISSIONING": "runtime_contract",
    "GraphSafety": "runtime_contract",
    "HARDWARE_PROBE_EVIDENCE_SOURCE": "path_safety",
    "LocalSubwoofer": "profile",
    "MAGNITUDE_ONLY": "crossover_alignment",
    "MAX_TEST_LEVEL_DBFS": "calibration_level",
    "MEASUREMENT_STATE_KIND": "measurement",
    "MIN_TEST_LEVEL_DBFS": "calibration_level",
    "NullTonePlaybackBackend": "playback",
    "OPERATOR_EVIDENCE_SOURCE": "path_safety",
    "OutputChannel": "profile",
    "OutputContract": "runtime_contract",
    "PATH_SAFETY_EVIDENCE_ENV": "path_safety",
    "PATH_SAFETY_EVIDENCE_KIND": "path_safety",
    "PHASE_AWARE": "crossover_alignment",
    "PathSafetyRequirement": "path_safety",
    "RAMP_ROLE_ORDER": "commission_ramp",
    "RAMP_STATE_ENV": "commission_ramp",
    "RAMP_STATE_KIND": "commission_ramp",
    "REQUIRED_PATHS": "path_safety",
    "ResolvedMode": "crossover_alignment",
    "SAFE_PLAYBACK_SESSION_KIND": "safe_playback",
    "SCHEMA_VERSION": "profile",
    "STAGED_CONFIG_PATH_ENV": "staging",
    "STAGED_METADATA_PATH_ENV": "staging",
    "STAGED_STARTUP_CONFIG_KIND": "staging",
    "STARTUP_HEADROOM_DB": "camilla_yaml",
    "STARTUP_LIMITER_CLIP_LIMIT_DB": "camilla_yaml",
    "STARTUP_LOAD_PREFLIGHT_KIND": "startup_load",
    "STARTUP_LOAD_STATE_ENV": "state_paths",
    "STARTUP_LOAD_STATE_KIND": "startup_load",
    "STATE_PATH_ENV": "calibration_level",
    "SUMMED_ACOUSTIC_KIND": "driver_acoustics",
    "SUMMED_VERDICTS": "driver_acoustics",
    "SUMMED_VERDICT_TO_OUTCOME": "commissioning_capture",
    "SafeGraphDecision": "runtime_contract",
    "SafetyEnvelope": "profile",
    "SpeakerBaselineProfile": "profile",
    "SummedAcousticResult": "driver_acoustics",
    "TONE_BACKEND_STATUS_KIND": "playback",
    "TONE_PLAN_KIND": "tone_plan",
    "TONE_PLAYBACK_ARTIFACT_KIND": "playback",
    "TONE_PLAYBACK_RESULT_KIND": "playback",
    "WavArtifactTonePlaybackBackend": "playback",
    "abort_ramp": "commission_ramp",
    "active_driver_targets": "measurement",
    "active_summed_targets": "measurement",
    "active_topology_requires_roleful_graph": "runtime_contract",
    "analyze_driver_capture": "driver_acoustics",
    "apply_baseline_profile": "baseline_profile",
    "arm_safe_playback_session": "safe_playback",
    "audible_outputs_for_role": "camilla_yaml",
    "baseline_candidate_fingerprint": "baseline_profile",
    "baseline_config_path": "baseline_profile",
    "baseline_profile_state_path": "baseline_profile",
    "build_baseline_profile_candidate": "baseline_profile",
    "build_bringup_preflight": "bringup",
    "build_crossover_alignment_proposal": "commissioning_capture",
    "build_crossover_preview": "crossover_preview",
    "build_design_draft": "design_draft",
    "build_driver_commission_load_preflight": "startup_load",
    "build_driver_research_prompt": "driver_safety",
    "build_driver_research_request": "driver_safety",
    "build_driver_safety_profile": "driver_safety",
    "build_passive_mains_preset": "staging",
    "build_stage5_ramp_gate": "commission_ramp",
    "build_startup_load_path_safety_evidence": "path_safety",
    "build_startup_load_preflight": "startup_load",
    "build_summed_topology_tone_plan": "topology_tone",
    "calibration_level_payload": "calibration_level",
    "channel_select_mixer_name": "camilla_yaml",
    "clamp_test_level_dbfs": "calibration_level",
    "classify_camilla_config_text": "environment",
    "classify_camilla_graph": "runtime_contract",
    "classify_mic_meter": "calibration_level",
    "classify_output_contract": "runtime_contract",
    "compile_preset_from_crossover_preview": "staging",
    "confirmed_driver_roles": "measurement",
    "crossover_preview_fingerprint": "crossover_preview",
    "declared_protection_floor_hz": "test_signal_plan",
    "declared_protection_highpass_floor_hz": "driver_protection",
    "driver_commission_audible_evidence": "graph_evidence",
    "driver_passband_hz": "commissioning_capture",
    "driver_protection_payload": "driver_protection",
    "driver_protection_profile": "driver_protection",
    "driver_test_signal_plan": "test_signal_plan",
    "driver_test_signal_plan_from_edges": "test_signal_plan",
    "effective_confirmed_roles": "commission_ramp",
    "emit_active_speaker_baseline_config": "camilla_yaml",
    "emit_active_speaker_commissioning_config": "camilla_yaml",
    "emit_active_speaker_driver_domain_config": "camilla_yaml",
    "emit_active_speaker_program_bake_config": "camilla_yaml",
    "emit_active_speaker_program_config": "camilla_yaml",
    "emit_active_speaker_startup_config": "camilla_yaml",
    "evaluate_driver_safety_profile": "driver_safety",
    "evaluate_path_safety_evidence": "path_safety",
    "load_active_speaker_preset": "tone_plan",
    "load_calibration_level_state": "calibration_level",
    "load_commission_load_state": "startup_load",
    "load_crossover_preview": "crossover_preview",
    "load_design_draft": "design_draft",
    "load_driver_commissioning_config": "startup_load",
    "load_measurement_state": "measurement",
    "load_protected_startup_config": "startup_load",
    "load_ramp_state": "commission_ramp",
    "load_safe_playback_state": "safe_playback",
    "load_staged_startup_config": "staging",
    "load_startup_load_state": "startup_load",
    "load_summed_commissioning_config": "startup_load",
    "lowest_driver_role": "profile",
    "measurement_state_path": "measurement",
    "next_ramp_gain_db": "commission_ramp",
    "normalise_driver_research": "design_draft",
    "normalise_manual_settings": "design_draft",
    "normalise_operator_inputs": "design_draft",
    "parse_aplay_playback_devices": "environment",
    "parse_camilla_statefile_config_path": "environment",
    "path_safety_evidence_path": "path_safety",
    "prepare_driver_commissioning_config": "staging",
    "primary_crossover_fc_hz": "commissioning_capture",
    "probe_active_speaker_environment": "environment",
    "propose_crossover_alignment": "crossover_alignment",
    "protection_highpass_floor_satisfied": "driver_protection",
    "protective_tweeter_highpass_frequency_hz": "test_signal_plan",
    "ramp_audible_step": "commission_ramp",
    "record_driver_acoustic_capture": "commissioning_capture",
    "record_driver_measurement": "measurement",
    "record_ramp_operator_ack": "commission_ramp",
    "record_safe_playback_result": "safe_playback",
    "record_summed_acoustic_capture": "commissioning_capture",
    "record_summed_test_artifact": "measurement",
    "record_summed_validation": "measurement",
    "required_driver_roles": "profile",
    "requirements_payload": "path_safety",
    "reset_ramp_state": "commission_ramp",
    "resolve_active_playback_device": "playback_route",
    "resolve_measurement_mode": "crossover_alignment",
    "rollback_driver_commissioning_config": "startup_load",
    "rollback_protected_startup_config": "startup_load",
    "running_commission_evidence": "graph_evidence",
    "safe_graph_for_current_topology": "runtime_contract",
    "save_crossover_preview": "crossover_preview",
    "save_design_draft": "design_draft",
    "stage_protected_startup_config": "staging",
    "start_tone_playback": "playback",
    "stop_safe_playback_session": "safe_playback",
    "stop_tone_playback": "playback",
    "strictest_crossover_highpass_hz": "test_signal_plan",
    "tone_backend_status": "playback",
    "update_calibration_level_state": "calibration_level",
    "validate_driver_research_request": "driver_safety",
    "validate_driver_research_result_shape": "driver_safety",
    "write_driver_sweep_wav": "driver_acoustics",
    "write_path_safety_evidence": "path_safety",
}

__all__ = sorted(_LAZY_ATTRS)


def __getattr__(name: str) -> Any:
    # Caching into globals() keeps the old eager re-export's binding
    # semantics: the name is resolved once, so patching the defining
    # submodule afterwards does not retarget it. jasper.multiroom's
    # __getattr__ deliberately does the opposite (#1270, #1678) — it
    # resolves per access because its callables are monkeypatched.
    module = _LAZY_ATTRS.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = getattr(import_module(f".{module}", __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *_LAZY_ATTRS})
