"""Active-speaker crossover commissioning substrate.

This package is intentionally pure Python and import-cheap. It models the
speaker-baseline layer, emits protected startup templates, and owns the
guarded startup-load/rollback boundary. It does not emit audio or grant
playback authority.
"""

from .profile import (
    ACTIVE_BASELINE_KIND,
    ACTIVE_PRESET_KIND,
    SCHEMA_VERSION,
    ActiveChannelMap,
    ActiveSpeakerConfigError,
    ActiveSpeakerPreset,
    BaselineVerification,
    CrossoverRegion,
    DriverSpec,
    OutputChannel,
    SafetyEnvelope,
    SpeakerBaselineProfile,
    required_driver_roles,
)
from .camilla_yaml import (
    ACTIVE_STARTUP_CONFIG_NAME,
    STARTUP_HEADROOM_DB,
    STARTUP_LIMITER_CLIP_LIMIT_DB,
    emit_active_speaker_startup_config,
)
from .path_safety import (
    HARDWARE_PROBE_EVIDENCE_SOURCE,
    OPERATOR_EVIDENCE_SOURCE,
    PATH_SAFETY_EVIDENCE_KIND,
    REQUIRED_PATHS,
    PathSafetyRequirement,
    evaluate_path_safety_evidence,
    requirements_payload,
)
from .environment import (
    ENVIRONMENT_REPORT_KIND,
    classify_camilla_config_text,
    parse_aplay_playback_devices,
    parse_camilla_statefile_config_path,
    probe_active_speaker_environment,
)
from .safe_playback import (
    SAFE_PLAYBACK_SESSION_KIND,
    arm_safe_playback_session,
    load_safe_playback_state,
    record_safe_playback_result,
    stop_safe_playback_session,
)
from .calibration_level import (
    CALIBRATION_LEVEL_KIND,
    DEFAULT_TEST_LEVEL_DBFS,
    STATE_PATH_ENV,
    MAX_TEST_LEVEL_DBFS,
    MIN_TEST_LEVEL_DBFS,
    calibration_level_payload,
    clamp_test_level_dbfs,
    classify_mic_meter,
    load_calibration_level_state,
    update_calibration_level_state,
)
from .tone_plan import (
    DEFAULT_PRESET_RESOURCE,
    TONE_PLAN_KIND,
    build_safe_tone_plan,
    load_active_speaker_preset,
    tone_targets_payload,
)
from .playback import (
    AplayTonePlaybackBackend,
    TONE_BACKEND_STATUS_KIND,
    TONE_PLAYBACK_ARTIFACT_KIND,
    TONE_PLAYBACK_RESULT_KIND,
    NullTonePlaybackBackend,
    WavArtifactTonePlaybackBackend,
    enabled_audio_backend,
    start_tone_playback,
    stop_tone_playback,
    tone_backend_status,
)
from .topology_tone import build_topology_tone_plan
from .staging import (
    ACTIVE_PLAYBACK_DEVICE_ENV,
    STAGED_CONFIG_PATH_ENV,
    STAGED_METADATA_PATH_ENV,
    STAGED_STARTUP_CONFIG_KIND,
    load_staged_startup_config,
    stage_protected_startup_config,
)
from .bringup import BRINGUP_PREFLIGHT_KIND, build_bringup_preflight
from .startup_load import (
    STARTUP_LOAD_PREFLIGHT_KIND,
    STARTUP_LOAD_STATE_ENV,
    STARTUP_LOAD_STATE_KIND,
    build_startup_load_preflight,
    load_protected_startup_config,
    load_startup_load_state,
    rollback_protected_startup_config,
)

__all__ = [
    "ACTIVE_STARTUP_CONFIG_NAME",
    "ACTIVE_BASELINE_KIND",
    "ACTIVE_PRESET_KIND",
    "CALIBRATION_LEVEL_KIND",
    "DEFAULT_PRESET_RESOURCE",
    "DEFAULT_TEST_LEVEL_DBFS",
    "ENVIRONMENT_REPORT_KIND",
    "HARDWARE_PROBE_EVIDENCE_SOURCE",
    "MAX_TEST_LEVEL_DBFS",
    "MIN_TEST_LEVEL_DBFS",
    "OPERATOR_EVIDENCE_SOURCE",
    "PATH_SAFETY_EVIDENCE_KIND",
    "REQUIRED_PATHS",
    "SAFE_PLAYBACK_SESSION_KIND",
    "SCHEMA_VERSION",
    "STATE_PATH_ENV",
    "STAGED_CONFIG_PATH_ENV",
    "STAGED_METADATA_PATH_ENV",
    "STAGED_STARTUP_CONFIG_KIND",
    "STARTUP_HEADROOM_DB",
    "STARTUP_LIMITER_CLIP_LIMIT_DB",
    "STARTUP_LOAD_PREFLIGHT_KIND",
    "STARTUP_LOAD_STATE_ENV",
    "STARTUP_LOAD_STATE_KIND",
    "TONE_PLAN_KIND",
    "TONE_BACKEND_STATUS_KIND",
    "TONE_PLAYBACK_ARTIFACT_KIND",
    "TONE_PLAYBACK_RESULT_KIND",
    "ACTIVE_PLAYBACK_DEVICE_ENV",
    "AplayTonePlaybackBackend",
    "ActiveChannelMap",
    "ActiveSpeakerConfigError",
    "ActiveSpeakerPreset",
    "BaselineVerification",
    "BRINGUP_PREFLIGHT_KIND",
    "CrossoverRegion",
    "DriverSpec",
    "OutputChannel",
    "PathSafetyRequirement",
    "NullTonePlaybackBackend",
    "SafetyEnvelope",
    "SpeakerBaselineProfile",
    "WavArtifactTonePlaybackBackend",
    "classify_camilla_config_text",
    "calibration_level_payload",
    "clamp_test_level_dbfs",
    "classify_mic_meter",
    "load_calibration_level_state",
    "emit_active_speaker_startup_config",
    "evaluate_path_safety_evidence",
    "build_safe_tone_plan",
    "build_bringup_preflight",
    "build_startup_load_preflight",
    "build_topology_tone_plan",
    "enabled_audio_backend",
    "load_active_speaker_preset",
    "load_protected_startup_config",
    "load_startup_load_state",
    "load_staged_startup_config",
    "parse_aplay_playback_devices",
    "parse_camilla_statefile_config_path",
    "probe_active_speaker_environment",
    "required_driver_roles",
    "requirements_payload",
    "arm_safe_playback_session",
    "load_safe_playback_state",
    "record_safe_playback_result",
    "rollback_protected_startup_config",
    "start_tone_playback",
    "stage_protected_startup_config",
    "stop_safe_playback_session",
    "stop_tone_playback",
    "tone_targets_payload",
    "tone_backend_status",
    "update_calibration_level_state",
]
